[베르] 1, 2단계 오목 제출합니다.
woowacourse/kotlin-omok pull request #20
Opened 2023-03-16 08:53 UTC by SeongHoonC

급하게 하느라 놓친 부분이 많은 것 같습니다ㅜ

리뷰 잘부탁드립니다!

2023-03-16 16:24 UTC, woowahan-leah requested changes
안녕하세요 베르! 이번 미션 함께하게 된 레아입니다.

오목 게임 구현을 잘 해주셨습니다 💯  쉽지 않은 구현이였을 텐데 고생 정말 많으셨습니다.
고민해보시면 좋을만한 코멘트를 달았으니 확인해주시면 감사하겠습니다.

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 💪

2023-03-20 13:41 UTC, woowahan-leah approved these changes
안녕하세요 베르! 
리뷰 반영을 잘 해주셨습니다 💯 코멘트를 많이 남겼는데 전부 반영하시느라 고생 많으셨어요.
그만큼 많은 성장을 이루신 것 같아 박수쳐드리고 싶어요 👏 

내일부터 안드로이드에 집중하시라는 의미에서 이 PR은 이만 마무리하겠습니다.
조금 고민해보시면 좋을 내용을 코멘트로 달았으니 다음 단계 미션 진행해주시면서 같이 반영해주시면 됩니다!

다음 미션도 화이팅입니다 🙏

2023-03-20 13:41 UTC, woowahan-leah commented on src/test/kotlin/model/domain/tools/CoordinationTest.kt
> +    @ParameterizedTest
ParameterizedTest 활용 👍

2023-03-20 13:41 UTC, woowahan-leah commented on src/test/kotlin/model/domain/state/EndTest.kt
> +class EndTest {
End 상태가 되는 경우의 수에 대한 테스트도 추가되면 좋겠습니다.

2023-03-20 13:42 UTC, merged

2023-03-21 06:15 UTC, SeongHoonC commented on src/main/kotlin/model/domain/tools/Board.kt
> +class Board private constructor(val system: MutableMap<Location, Stone>) {
방어적 복사..깜빡했네요ㅜ 반영하겠습니다!