[토마스] 3, 4단계 오목 제출합니다.
woowacourse/kotlin-omok pull request #52
Opened 2023-03-27 07:07 UTC by ki960213

안드로이드 스튜디오를 켜기만 하면 자동으로 꺼지는 문제가 발생해서 주말 동안 코딩할 수 없었습니다.
플러그인 버전 문제였다는 것을 어제 밤에 깨달았습니다.
그래서 오늘 구현하느라 시간이 부족했습니다.
다음 리뷰 반영할 때 이전 리뷰까지 반영하겠습니다.
stpe2 때 정성스러운 리뷰 감사합니다!

2023-03-27 14:21 UTC, BeokBeok commented on app/src/main/java/woowacourse/omok/MainActivity.kt
> +    private var toast: Toast? = null
toast를 멤버 변수로 잘 정의해주셨네요. 👍 
다만, toast는 모든 activity에서 활용할 수 있습니다.
그렇다면 toast와 관련된 코드를 클래스로 관리해보면 어떨까요?

2023-03-27 14:28 UTC, BeokBeok commented on app/src/main/java/woowacourse/omok/repository/StoneRepository.kt
> +    private val db = StoneDbHelper(context).writableDatabase
```suggestion
class StoneRepository(private val db: SQLiteDatabase) {
```
context는 SQLiteDatabase를 만들기 위해서만 사용하고 있어요.
그렇다면, SQLiteDatabase를 캡슐화하도록 개선해보면 어떨까요?

2023-03-29 13:32 UTC, BeokBeok requested changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2023-03-29 13:32 UTC, BeokBeok commented on app/src/main/java/woowacourse/omok/MainActivity.kt
> +    }
하나의 함수에서 두 가지 이상의 일을 하고 있어요. (OmokGame 객체 생성, 돌 생성 등)
하나의 함수에는 한 가지 일만 할 수 있도록 개선해보면 어떨까요?

2023-03-29 13:32 UTC, BeokBeok commented on app/src/main/java/woowacourse/omok/MainActivity.kt
> +        stoneRepository.insert(Stone(omokGame.lastPoint!!))
omokGame.lastPoint가 반드시 null이 아님을 보장할 수 있을까요?

2023-03-29 13:32 UTC, BeokBeok commented on domain/src/main/kotlin/domain/Board.kt
> +        get() = boardStones.values.flatMap { it.stones.map { stone -> stone.point } }.toSet()
객체 지향 생활 체조 원칙에는 아래와 같은 항목이 있습니다.
- 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

위 원칙을 지켜보면 어떨까요? (이하 관련 내용 동일)

2023-03-29 13:32 UTC, BeokBeok commented on domain/src/main/kotlin/domain/Board.kt
> +    operator fun get(team: Team): Stones = boardStones[team]!!
non-null assertion(!!)을 활용해주셨네요.
non-null assertion을 사용하게 되면, 간단하게 nullable을 non-null로 가정하고 코드를 작성할 수 있는 장점이 있습니다.
하지만, null일 경우에는 exception이 발생하게 됩니다.
전반적으로 null-safe하게 코드를 개선해보면 어떨까요?

2023-03-29 13:32 UTC, BeokBeok commented on domain/src/main/kotlin/domain/Board.kt
> +    private val boardStones = Team.values().associateWith { Stones() }
Board는 Team에 대해서 너무 잘 알고 있어요.
디미터 법칙에 대해서 학습해보시고, Team에 메시지를 보내도록 개선해보면 어떨까요?

2023-03-29 13:32 UTC, BeokBeok commented on domain/src/main/kotlin/domain/OmokGame.kt
> +    }
OmokGame 객체를 생성하게 되면 startEventManager의 notify 함수가 호출될 것이라는 것을 인지할 수 있을까요?
init 블록의 역할에 대해서 학습해보시고 어떻게 개선하면 좋을지 고민해보면 어떨까요?

2023-03-29 13:41 UTC, ki960213 commented on app/src/main/java/woowacourse/omok/MainActivity.kt
> +        stoneRepository.insert(Stone(omokGame.lastPoint!!))
non-null assertion을 사용한 이유는 만약 널일 경우 에러가 발생하는 것을 감수하겠다는 의미로 사용했습니다.
돌을 뒀을 때 이벤트가 발생했는데, 돌이 하나도 없어서 마지막 좌표가 null이라는 것은 논리 오류이므로 의도적으로 non-null assertion을 사용했습니다.
혹시 이러한 경우에도 non-null assertion을 지양해야 하나요?

2023-03-29 14:00 UTC, ki960213 commented on domain/src/main/kotlin/domain/Board.kt
> +        get() = boardStones.values.flatMap { it.stones.map { stone -> stone.point } }.toSet()
다른 프로퍼티로부터 유도되는 프로퍼티도 메서드 호출을 통해 얻을 수 있도록 바꾸는 게 좋을까요?

2023-03-29 14:00 UTC, ki960213 commented on domain/src/main/kotlin/domain/Board.kt
> +    operator fun get(team: Team): Stones = boardStones[team]!!
오목판은 모든 팀의 돌을 놓을 수 있어야 하기 때문에 의도적으로 non-null assertion을 사용했습니다.
만약 오목판의 돌들 중 어떤 팀은 접근할 수 없다면 그것은 논리 오류라고 생각해서 에러가 발생하도록 구현했습니다.
혹시 이러한 경우에도 non-null assertion을 지양하는 것이 좋을까요?

2023-03-29 14:02 UTC, BeokBeok commented on app/src/main/java/woowacourse/omok/MainActivity.kt
> +        stoneRepository.insert(Stone(omokGame.lastPoint!!))
논리 오류에 대해서 잘 말씀해주셨습니다. 👍 
다만, NPE(Null Pointer Exception)은 해당 데이터가 null일 경우에 대한 오류를 가리키며, 마지막 좌표가 null 일 경우를 의미하는 오류를 가리키는 것은 아닙니다.
의도하신대로 마지막 좌표가 없을 경우에 대한 논리 오류를 표현하고자 하신다면, NPE가 아닌 마지막 좌표와 관련된 Exception을 구현해보면 어떨까요?

2023-03-29 14:04 UTC, BeokBeok commented on domain/src/main/kotlin/domain/Board.kt
> +        get() = boardStones.values.flatMap { it.stones.map { stone -> stone.point } }.toSet()
말씀하신 것도 여러 방법 중 하나입니다. 😄

2023-03-29 14:06 UTC, BeokBeok commented on domain/src/main/kotlin/domain/Board.kt
> +    operator fun get(team: Team): Stones = boardStones[team]!!
https://github.com/woowacourse/kotlin-omok/pull/52#discussion_r1151996351

위 부분 참고해주세요. 🙏 
추가로 논리 오류의 개념은 아래와 같습니다.
> 컴퓨터 프로그래밍에서 프로그램이 부정확하게 동작하게 하지만 비정상적으로 종료 또는 충돌시키지는 않는 버그이다.

하지만, 안드로이드에서는 일반적으로 NPE(Null Pointer Exception)을 만나게 되면, 앱이 강제 종료가 됩니다.
그렇다는 것은, NPE는 논리 오류가 아닙니다. 😅 
Null Pointer Exception이 무엇인지 학습해보시면 어떨까요?

2023-03-29 14:17 UTC, BeokBeok commented on domain/src/main/kotlin/domain/Board.kt
> +    operator fun get(team: Team): Stones = boardStones[team]!!
혼동되실 것 같아 위 코맨트는 숨김처리하였습니다.
아래 부분에 대해서만 집중해주시면 좋을 것 같습니다. 🙏 
- NPE가 말씀하신 오류의 의미와 동일한지
- NPE는 무엇인지

2023-03-29 14:19 UTC, ki960213 commented on domain/src/main/kotlin/domain/Board.kt
> +    private val boardStones = Team.values().associateWith { Stones() }
enum class의 values 메소드는 언어에서 기본적으로 제공되는 메서드라서 enum class의 모든 값들에 대해 연산을 하고 싶다면 values 메소드를 사용해도 된다고 생각했습니다.
원하는 연산을 하는 메소드를 따로 만드는 것이 더 좋은 방법일까요? 예를 들면
`private val boardSteons = Team.associateWith { Stones() }`
위 코드처럼 values 메소드를 사용하지 않고 곧바로 Map<Team, Stones> 인스턴스를 만들 수 있도록 하는 것이 더 좋은 방법인가요?

2023-03-29 14:28 UTC, ki960213 commented on app/src/main/java/woowacourse/omok/MainActivity.kt
> +        stoneRepository.insert(Stone(omokGame.lastPoint!!))
논리 오류가 발생할 경우 에러가 발생하지 않는다면 논리 오류를 찾는 것이 더 힘들기 때문에 의도적으로 NPE라도 발생시켜서 논리 오류가 발생했다는 것을 알 수 있도록 하고자 non-null assertion을 사용했습니다. 
```kotlin
    override fun notifyPlaceStoneEventHasOccurred(omokGame: OmokGame) {
        val lastPoint = omokGame.lastPoint ?: return
        drawRunningBoardView(omokGame)
        stoneRepository.insert(Stone(lastPoint))
    }
```
위 코드처럼 그냥 넘어간다면 돌을 놓았음에도 오목 게임의 마지막 돌의 좌표가 null이라는 논리 오류를 발견하지 못할테니까요.
하지만 생각해보니 관련된 Exception을 구현하는 것이 더 명확하군요!

2023-03-30 13:05 UTC, BeokBeok commented on domain/src/main/kotlin/domain/Board.kt
> +    private val boardStones = Team.values().associateWith { Stones() }
Team에서 associateWith가 된 값을 전달하게 하면 가장 좋습니다.

2023-03-30 13:14 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
좋은 개발자가 되기 위한 소중한 경험이 되었길 바랍니다. 💪

2023-03-30 13:14 UTC, BeokBeok commented on app/src/main/java/woowacourse/omok/repository/StoneRepository.kt
> +        }
객체 지향 생활 체조 원칙에는 아래와 같은 항목이 있습니다.
- 한 메서드에 오직 한 단계의 들여쓰기만 한다.

위 원칙을 지켜보면 어떨까요?

2023-03-30 13:14 UTC, BeokBeok commented on domain/src/main/kotlin/view/OutputView.kt
>          check(lastPoint != null) { LAST_POINT_IS_NULL_ERROR }
프로그래밍에서는 에러를 대처하는 방법이 두 종류가 있습니다.
- 오류가 예상되는 경우
- 오류가 예상되지 않는 경우

오류가 예상되는 경우에는 주로 null 또는 기본값을 리턴합니다.
반면, 오류가 예상되지 않는 경우에는 Exception을 던지도록 구현합니다.
저번에 말씀하셨듯이, lastPoint가 null인 경우는 마지막 좌표가 null임을 의미한다고 하셨습니다.
그렇다는 것은 어떤 오류인지 예상되는 경우로써, Exception이 아닌 다른 방법을 활용하는 것이 좋습니다.

ref. https://elizarov.medium.com/kotlin-and-exceptions-8062f589d07

2023-03-30 13:14 UTC, BeokBeok commented on domain/src/main/kotlin/view/OutputView.kt
>          check(lastPoint != null) { LAST_POINT_IS_NULL_ERROR }
안드로이드에서는 Exception을 만나게되면 앱이 비정상적으로 종료가 되게 됩니다.
해서, Exception이 발생하게 되면, Exception이 발생하지 않도록 개선할 수 있어야 합니다.
만약 유저가 마지막 좌표가 null일 경우를 자주 접하게 된다면 이 앱은 비정상적으로 종료가 되며, 이는 곧 사용자의 이탈로 이루어지게 됩니다.
이 부분에 대해서 한번 고민해보시면 좋을 것 같아요.

2023-03-30 13:14 UTC, merged

2023-03-31 00:57 UTC, ki960213 commented on domain/src/main/kotlin/view/OutputView.kt
>          check(lastPoint != null) { LAST_POINT_IS_NULL_ERROR }
저는 lastPoint가 null일 경우가 오류가 예상되는 경우라는 것이 잘 이해가 되지 않습니다.
onStonePlaced 메서드는 돌이 놓였을 때 호출되어야 한다고 정의했습니다. onStonePlaced가 호출되었는데도 lastPoint가 null이라는 것은 어딘가에 로직이 잘못되었다는 것을 의미한다고 생각합니다. 그래서 저는 오류가 예상되지 않는 경우라고 생각합니다.

2023-03-31 01:01 UTC, BeokBeok commented on domain/src/main/kotlin/view/OutputView.kt
>          check(lastPoint != null) { LAST_POINT_IS_NULL_ERROR }
오류가 예상되지 않는다면, non-null하게 만들 수 있지 않을까요?

2023-03-31 01:04 UTC, BeokBeok commented on domain/src/main/kotlin/view/OutputView.kt
>          check(lastPoint != null) { LAST_POINT_IS_NULL_ERROR }
말씀하신대로라면 모든 경우가 어떤 오류가 발생하게 될 지 예상되지 않기 때문에, 모든 변수의 타입들을 nullable하게 만들어야하지 않을까요? 🤔

2023-03-31 01:11 UTC, ki960213 commented on domain/src/main/kotlin/view/OutputView.kt
>          check(lastPoint != null) { LAST_POINT_IS_NULL_ERROR }
OmokGame의 lastPoint가 null일 수는 있다고 생각합니다. 하지만 onStonePlaced 메서드가 실행될 때는 lastPoint가 null이라면 어딘가의 로직이 잘못되었다고 생각합니다. 그래서 lastPoint의 반환값의 타입을 nullable로 선언했습니다.

2023-03-31 01:13 UTC, BeokBeok commented on domain/src/main/kotlin/view/OutputView.kt
>          check(lastPoint != null) { LAST_POINT_IS_NULL_ERROR }
실제로 오목게임을 하시면서 lastPoint가 null인 경우가 있었나요?

2023-03-31 01:54 UTC, ki960213 commented on domain/src/main/kotlin/view/OutputView.kt
>          check(lastPoint != null) { LAST_POINT_IS_NULL_ERROR }
오목 게임이 만들어지자 마자 lastPoint를 요청하면 null일 수 있다고 생각합니다.

2023-03-31 02:16 UTC, BeokBeok commented on domain/src/main/kotlin/view/OutputView.kt
>          check(lastPoint != null) { LAST_POINT_IS_NULL_ERROR }
그렇다면 오목 게임이 만들어지자마자 lastPoint에 요청하지 못하도록 개선해보면 어떨까요?
말씀하신것처럼 충분히 예상되는 오류는 단순히 Exception을 발생시키는것보다는 오류가 발생할 케이스를 방지하고 수정하는 것이 좋지 않을까요?
논리적 오류라고 해서 Exception이 발생하는 것을 방치한다면, 프로그램을 사용하다가 갑자기 비정상적으로 종료되는 케이스를 접하게 되는 사용자는 부정적인 경험을 갖게 되지 않을까요?

2023-03-31 04:18 UTC, BeokBeok commented on domain/src/main/kotlin/view/OutputView.kt
>          check(lastPoint != null) { LAST_POINT_IS_NULL_ERROR }
구체적으로 답변해주셔서 토마스의 생각을 알 수 있어서 좋았습니다. 👍 

먼저 저의 생각을 말씀드려보겠습니다.
"예상되지 않는 오류"란, 무언가를 했는지는 모르지만 에러가 발생하는 경우를 말합니다.
하지만, 토마스의 말씀을 들어보니 어떤 경우에 에러가 발생하는지를 말씀해주셨기에 저는 "예상되는 오류"로 보였습니다.
Exception을 사용하는 이유는, 개발자에게 프로그램의 오류를 알려서 빠르게 수정하기 위함입니다.
예상되지 않는 오류이니 Exception이 발생해서 비정상적으로 종료되는것이 당연한 것이 아님을 알아주셨으면 좋겠습니다.

마지막으로, 개발에는 정답이 없으나 아래 항목들에 대해서 학습을 해보신 후 스스로 답을 내려보셨으면 좋겠습니다. 🙏 
- null이 무엇일까요?
- 객체지향 관점에서의 null은 어떤 의미를 가지고 있을까요?
- 일급객체 혹은 일급컬렉션은 무엇일까요?