[해시] 1, 2단계 오목 제출합니다.
woowacourse/kotlin-omok pull request #6
Opened 2023-03-16 07:52 UTC by EmilyCh0

안녕하세요 리뷰어님! 이번 미션 잘부탁드립니다 😄

미션 진행하면서 궁금한 점이 생겨 질문 남깁니다!

- board.value에 직접 접근해서  `move()`와 `isEmpty()`를 실행할 수도 있지만 디미터 법칙을 준수하기 위해서 board에도 `move()`와 `isEmpty()`를 작성해서 결과를 전달하도록 했습니다.
    객체를 깊게 탐색하지 않는다는 장점이 있지만 move라는 메서드를 파악하려면 코드를 타고 들어가야 해서 코드를 파악하기에 불편하다는 단점이 있다고 생각합니다. 
    그리고 테스트 코드를 작성할 때도 OmokBoard의 `move()`와 Board의 `move()`가 결국에는 비슷한 테스트를 하는 것 같아 불필요한 중복 테스트가 아닌가 하는 생각도 듭니다.
    

그리고 금수 알고리즘 자체는 미션의 목표가 아니라서 다른 크루의 코드(rule 패키지 내부 코드)를 사용했고, 이를 제 코드에 적용하기 위한 어댑터를 만들었습니다.

2023-03-17 02:25 UTC, galcyurio requested changes
오목 1, 2단계 구현 고생하셨습니다 :)
몇 가지 피드백을 남겨두었으니 확인 후 다시 요청해주세요!

2023-03-17 02:25 UTC, galcyurio commented on src/main/kotlin/Controller.kt
> +class Controller {
InputView, OutputView에 대한 직접적인 의존성 때문에 Controller는 테스트가 불가능한 상태입니다.
느슨하게 결합하도록 변경해보세요.

제대로 피드백이 반영된다면, OmokController는 다음 단계인 안드로이드에서도 그대로 사용할 수 있어야 합니다.

2023-03-17 02:25 UTC, galcyurio commented on src/main/kotlin/domain/OmokRuleAdapter.kt
> +    }
indent가 너무 깊습니다. 
지역 변수나 함수로 분리해보세요.

2023-03-17 02:25 UTC, galcyurio commented on src/main/kotlin/domain/Stone.kt
> +    }
UI 로직입니다. GUI에서 그림으로 표현해야하는 경우에 어떻게 대응할 수 있을까요?

2023-03-17 02:25 UTC, galcyurio commented on src/main/kotlin/domain/OmokGame.kt
> +        onFinish: (State) -> Unit
`runGame()`에서 콜백 함수들을 모두 받아서 처리하는 대신 OmokGame 자체에 Listener를 추가하는 방식으로 변경해보세요.

Listener 방식으로 변경된 함수의 경우 다른 함수들에서도 매개변수가 사라져야 합니다.

2023-03-17 02:25 UTC, galcyurio commented on src/main/kotlin/domain/board/OmokBoard.kt
> +}
> board.value에 직접 접근해서 move()와 isEmpty()를 실행할 수도 있지만 디미터 법칙을 준수하기 위해서 board에도 move()와 isEmpty()를 작성해서 결과를 전달하도록 했습니다.
객체를 깊게 탐색하지 않는다는 장점이 있지만 move라는 메서드를 파악하려면 코드를 타고 들어가야 해서 코드를 파악하기에 불편하다는 단점이 있다고 생각합니다.
그리고 테스트 코드를 작성할 때도 OmokBoard의 move()와 Board의 move()가 결국에는 비슷한 테스트를 하는 것 같아 불필요한 중복 테스트가 아닌가 하는 생각도 듭니다.

Board에 대한 역할과 책임이 2개의 객체로 파편화되었습니다.
하나의 객체로 합쳐보세요.

2023-03-17 02:25 UTC, galcyurio commented on src/main/kotlin/domain/rule/ArkBoard.kt
> +}
> 금수 알고리즘 자체는 미션의 목표가 아니라서 다른 크루의 코드(rule 패키지 내부 코드)를 사용했고, 이를 제 코드에 적용하기 위한 어댑터를 만들었습니다.

현재는 package로 분리되어있는데 이런 경우에는 별도 모듈로 분리해주시면 좋습니다.
다만 지금 반영하려면 프로젝트가 멀티 모듈 프로젝트로 개념 자체가 바뀌어야해서 조금 어려울 수 있으니 3, 4 단계에서 반영해보면 좋겠습니다.

2023-03-17 02:25 UTC, galcyurio commented on src/main/kotlin/view/Color.kt
> +}
UI layer를 위한 별도의 클래스 :+1: 

`State`를 위한 클래스이므로 `StateUiModel`과 같이 만들어주면 이름을 통해 서로의 관계를 명확하게 할 수 있습니다.

2023-03-17 02:25 UTC, galcyurio commented on src/main/kotlin/view/OutputView.kt
> +    }
State를 UI layer의 Color로 변경하는 로직은 Color.kt 파일의 top-level에 선언해주시는게 좋습니다.
현재는 프로젝트가 작아서 한 곳에서만 쓰이지만 조금만 커져도 여러 View에서 접근하는 경우가 많습니다.

2023-03-18 06:54 UTC, EmilyCh0 commented on src/main/kotlin/Controller.kt
> +class Controller {
Controller 생성 시점에 InputView, OutputView를 주입하도록 변경했습니다.

2023-03-18 06:55 UTC, EmilyCh0 commented on src/main/kotlin/domain/Stone.kt
> +    }
OutputView의 메서드에서 stone을 받아 UI 로직을 처리하도록 변경했습니다. GUI에서 그림으로 표현하는 경우에도 마찬가지로 stone 받아 그림 형식에 맞게 처리하도록 해야 할 것 같습니다.

2023-03-18 06:56 UTC, EmilyCh0 commented on src/main/kotlin/domain/OmokGame.kt
> +        onFinish: (State) -> Unit
콜백 함수를 인자로 하나씩 전달하기보다는 콜백 함수들이 들어있는 Listener 인터페이스를 추가하고 Controller에서 이를 구현해 OmokGame으로 전달하도록 했습니다.

2023-03-18 06:57 UTC, EmilyCh0 commented on src/main/kotlin/domain/rule/ArkBoard.kt
> +}
넵 3, 4 단계에서 모듈로 분리해 보겠습니다!

2023-03-18 06:58 UTC, EmilyCh0 commented on src/main/kotlin/view/OutputView.kt
> +    }
함수를 StateUiModel 파일의 top-level로 옮겼습니다. top-level 함수를 사용하는 것과, StateUiModel의 companion object 내부에 함수를 두고, Companion 객체를 통해 함수를 실행하는 것(`StateUiModel.selectState()`)과의 차이가 궁금합니다!

2023-03-19 05:09 UTC, galcyurio approved these changes
피드백 잘 반영해주셨네요 👍️
이번 피드백은 다음 단계에서 같이 반영해주시면 됩니다 🙂

2023-03-19 05:09 UTC, merged