[오목] 누누 1, 2단계 미션 제출합니다.
woowacourse/kotlin-omok pull request #61
Opened 2024-03-21 08:02 UTC by jinuemong

### 안녕하세요 두루! 오목 미션 리뷰이로 매칭된 누누입니다 

잘 부탁드립니다🙇‍♂️

2024-03-22 02:21 UTC, Gyuil-Hwnag requested changes
누누 안녕하세요!
이번 미션을 함께하게 된 두루라고 합니다. 잘부탁드립니다!

오목 미션 구현을 하시느라 정말 고생 많으셨습니다!!💯

고민해보시면 좋을만한 내용들 코멘트를 달았으니 확인해주시면 감사하겠습니다.
추가적으로 우선적으로 klint 에서 걸리는 부분이 많아서 klint를 돌려보고 수정후에 코멘트를 반영해보는 것이 좋을 것 같습니다!💪

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 
화이팅입니다💪

2024-03-22 02:21 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/Board.kt
> +    private fun bfs(
bfs 라는 네이밍은 추후 기능이 확장되면 오해를 일으킬 수도 있다는 생각이 듭니다🤔

2024-03-22 02:21 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/Board.kt
> +                }
when 에서는 `is` 라는 키워드가 존재를 하는데, `is` 와 `::class` 와는 어떤 차이점이 있을까요??🤔

2024-03-22 02:21 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/Board.kt
> +            }
flag 값을 수정하는 내용 때문에 1뎁스가 더 깊어지는 것 같은데, 이럴경우 `do-while`을 사용해보는 것은 어떨지 고민해보면 좋을 것 같습니다~💪
https://kotlinlang.org/docs/control-flow.html#while-loops

2024-03-22 02:21 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/CalculateType.kt
> +                ThreeToThreeCount -> "3-3 금수를 어겼습니다."
하드코딩된 값에 대해서는 상수화를 해서 적용을 해보도록 수정을 해봐도 좋을 것 같다는 생각이 듭니다💪

2024-03-22 02:21 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/Stone.kt
> +        }
해당 내용을 초기화 하는 부분과, 변수영역으로 분리를 해볼 수도 있겠다는 생각이 듭니다💪

2024-03-22 02:21 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/view/OutputView.kt
> +    }
전체적으로 코드 정렬 부탁드립니다!!🥲

2024-03-22 02:21 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/view/OutputView.kt
> +    }
해당 내용은 stone의 toString() 오버라이딩을 활용해보도록 수정해봐도 좋을 것 같다는 생각이 듭니다!💪

2024-03-22 02:21 UTC, Gyuil-Hwnag commented on src/test/kotlin/omock/BlackPlayerTest.kt
> +class BlackPlayerTest {
테스트 코드 전반적인 코멘트 입니다!!
klint 를 지켜주세요~😥

2024-03-22 02:21 UTC, Gyuil-Hwnag commented on src/test/kotlin/omock/BlackPlayerTest.kt
> +            )
test fixture 라는 개념이 존재하는데, 해당 내용을 살펴보면 초기화 하는 부분들이 좀 더 유연하게 수정이 될 수 있겠다는 생각이 듭니다!💪

2024-03-24 09:09 UTC, jinuemong commented on src/main/kotlin/omock/model/Board.kt
> +            }
do-while을 활용해서 수정해봤는데 코드 라인이 감소했습니다.
다만 flag를 활용하지 않는 방법이 어렵네요.. 힌트가 있을까요?

2024-03-24 09:22 UTC, jinuemong commented on src/main/kotlin/omock/model/Board.kt
> +                }
is 키워드는 특정 타입의 인스턴스인지 확인하고, ::class는 객체의 클래스를 가져올 때 사용합니다.
각 객체의 클래스를 비교하기 위해서 ::class를 사용했지만, 뭔가 보기 좋아보이지 않다는 생각을 합니다..
좋은 방법을 찾고있는데, 클래스에서 타입만 추론하는 방법이 있을까요? ㅠ 어렵네요

2024-03-24 18:24 UTC, jinuemong commented
[1차 리팩토링]
안녕하세요 리뷰어님! 
1차 리팩토링 과정을 거쳤습니다.
대부분 린트 체크 & 코드 정렬에 문제가 있어서 수정사항에 적용하였습니다.
이번 오목 미션이 시간이 부족하다는 생각이 많이 들어서 함수 분리에 시간을 많이 투자하지 못했던 것 같습니다.
수정한 부분은 🚀 이모지 달았구, 좀 어려웠던 부분에 👀 달아놨습니다.

2024-03-25 03:57 UTC, jinuemong commented on src/main/kotlin/omock/model/BlackPlayer.kt
> +            if (!isReverseTwoAndThree && (reverseResultCount + result.count >= MIN_O_MOCK_COUNT)) return true
하나의 기능을 하도록 수정해보려 했는데 반복적인 코드가 계속 발생합니다.
최대한 분리 해봤는데 감이 안오네요.. 반복되는 코드가 생기더라도 하나의 함수가 하나의 기능이 하는게 좋은가요?

2024-03-25 08:40 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/BlackPlayer.kt
> +            if (!isReverseTwoAndThree && (reverseResultCount + result.count >= MIN_O_MOCK_COUNT)) return true
오히려 분리를 하면서 가독성이 안좋아진다면, 안하는 것이 나을 것 같다는 생각입니다!!👍

2024-03-25 08:49 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/Board.kt
> +                }
현재 구현을 살펴보면, StoneState에 대해서 상속받은 객체들에 대해서 비슷한 기능을 하게 구현이 되어 있는 것들이 많은 것 같은데, 추상 클래스나 selaed class를 활용해보는 방법으로도 가독성을 향상시켜볼 수 있겠다는 생각이 듭니다!!

2024-03-25 08:58 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/Board.kt
> +            }
확실히 flag 관련된 내용이 많다고 생각이 들긴 합니다🥲
많이 어려울 수도 있겠다는 생각이 들긴 하는데, 아래와 같이 작은것부터 하나하나 객체를 수정해보는 것은 어떨까라는 생각이 듭니다!
- Board, Player 에서 다음 돌을 두는 판단을 하는 로직을 분리한다.
- 금수에 대한 판단을 하는 객체를 생성한다(3x3, 4x4, 5목판단)
- 다음 돌을 두는 로직을 담당하는 객체에서 금수를 판단하여, 둘 수 있는지에 대한 결과를 알려준다.

해당 미션의 경우, 이전 기수및 다른 크루들의 구현을 참고해도 되므로, 위의 규칙들에 맞도록 수정을 해보는 것이 좋을 것 같다는 생각이 듭니다!
누누가 구현하신 내용을 보면, 책임을 가지고 있지는 않으며, 단순히 원시값 포장만이 되어 있으며, 중요한 로직은 Player, Board 내에서 전부 담당을 하고 있어서 그렇지 않을까 라는 생각이 듭니다😥

2024-03-25 09:36 UTC, Gyuil-Hwnag requested changes
누누 안녕하세요!

해당 미션 구현 고생 많으셨습니다!
리뷰 반영하면서 구현한 내용 수정 너무 잘 해주셨습니다 💯

현재 구현을 보면 Player 에서 너무 오목에 대한 규칙을 체크하는등의 너무 많은 책임을 지고 있다는 생각이 듭니다🥲
고민해보시면 좋을만한 내용들 코멘트를 달았으니 확인해주시면 감사하겠습니다.

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 
화이팅입니다💪

2024-03-25 09:36 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/Black.kt
> +class Black(private val stone: Stone) : Placed(stone)
model 패키지에 대한 전반적인 코멘트 입니다!
가독성을 위하여 model 패키지 내에서도 Stone, Player, Board, Position(Row, Column) 등으로 분리해보는 것은 어떤가 라는 생각이 듭니다~💪

2024-03-25 09:36 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/BlackPlayer.kt
> +    }
해당 내용에 대해서는 Player 에서 담당하지 않고, Rule 이라는 객체로 분리를 해보는 방법을 고민해보는 것도 좋을 것 같습니다💪
현재 구현을 보면 Player 에서 너무 많은 것을 담당하고 있다는 생각이 듭니다🥲

2024-03-25 09:36 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/BlackPlayer.kt
> +    }
금수를 체크하는 것은 과연 Player 에서 담당을 해야 하는 것인지 고민해보면 좋을 것 같습니다🤔

2024-03-25 09:36 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/BlackPlayer.kt
> +        }
해당 내용은 return 타입으로 type을 반환하도록 하면, `객체 지향 생활 원칙`에 좀 더 적합하게 수정이 될 수 있지 않을까 라는 생각이 듭니다👍

2024-03-25 09:36 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/BlackPlayer.kt
> +    }
과연 해당 로직들도 Player 에서 담당을 해야 하는 것인지에 대한 의문이 생깁니다🤔

2024-03-26 07:59 UTC, jinuemong commented
[2차 리팩토링]
player와 board의 책임이 너무 많다고 생각하여, 의존성을 분리해보았습니다.

2024-03-26 15:01 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/rule/OMockRuleInterface.kt
> +        visitedFirstClear: Map<Direction, DirectionFirstClearResult>,
`Map<Direction, DirectionResult>`도 원시값 포장을 하여 책임을 가지도록 해보는 것은 어떨까 라는 생각이 듭니다!🤔

2024-03-26 15:01 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/stone/Stone.kt
> +        }
해당 내용은 View의 책임일지, Stone의 책임일지 고민해보면 좋을 것 같다는 생각이 듭니다!🤔

2024-03-26 15:04 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/view/OutputView.kt
> +        print("위치를 입력하세요:")
하드 코딩된 내용들에 대해서 상수화를 하며, 의미를 부여하고 유의미하게 사용을 해보는 것은 어떨지 고민해보면 좋을 것 같다는 생각이 듭니다!💪

2024-03-26 15:06 UTC, Gyuil-Hwnag commented on src/test/kotlin/omock/BoardTest.kt
> +        )
board를 생성하는 함수를 활용해주셨군요~👍

2024-03-26 15:06 UTC, Gyuil-Hwnag commented on src/test/kotlin/omock/BoardTest.kt
> +    fun `플레이어가 돌을 놓을 때, direction에 따른 정상적인 돌 개수 반환한다`() {
성공하는 테스트도 있으니, 실패하는 경우에 대해서도 한번 테스트 코드를 작성해봐도 좋을 것 같다는 생각이 듭니다!💪

2024-03-26 15:08 UTC, Gyuil-Hwnag commented on src/test/kotlin/omock/ColumnTest.kt
> +    }
테스트 코드 너무 잘 작성해주셨습니다!👍
반드시 추가가 필요한 것은 아닙니다! Junit의 기능들을 활용해 보는 것은 어떨까라는 생각이 듭니다💪

2024-03-26 15:10 UTC, Gyuil-Hwnag commented on src/test/kotlin/omock/OmockRuleTest.kt
> +    }
테스트 함수명을 `행위 -> 결과`에 맞게 너무 잘 작성해주셨네요~👍
너무 잘 작성해주셨는데, 한번 고민해보면 좋을 내용인 것 같아서 코멘트 달아두었습니다!
테스트 코드의 내용을 아래와 같이 `주어진 것` -> `행위, 행동` -> `결과`와 같은 흐름으로 작성을 해보는 것은 어떨까 합니다!💪
~~~kotlin
@Test
fun `자동차가 1칸 이동하면 거리는 1이다`() {
// given
val myCar = Car("Duru")

// when
myCar.move(1)

// result
assertThat(myCar.distance).isEqualTo(1)
}
~~~

2024-03-27 01:53 UTC, jinuemong commented on src/main/kotlin/omock/model/board/ColumnStates.kt
> +data class ColumnStates(
1급 컬렉션을 위해서 중첩 list를 포장했습니다.
행마다 책임을 부여하고 싶었습미다

2024-03-27 05:39 UTC, jinuemong commented on src/main/kotlin/omock/controller/OMokController.kt
> +    }
판을 변경하는 부분은 수정했습니다.
다만 outputview나 borad를 rollback 하는 부분도 controller에 있으면 안되는 것일까요?
board를 컨트롤러에서 생성해서 board의 함수를 호출하고 있습니다

2024-03-27 06:10 UTC, jinuemong commented on src/main/kotlin/omock/model/board/Board.kt
> +class Board(val stoneStates: List<ColumnStates>) {
클래스로 지정하면 안될까요?
이번에 gameTurn을 Board 내부에 저장해서 상태를 관리하도록 하였습니다.
게임의 상태를 관리하고, 규칙을 적용하여 플레이어 입력에 반응하도록 하였는데 클래스가 아닌 다른 방법이 있는지 궁금합니다

2024-03-27 06:13 UTC, jinuemong commented on src/main/kotlin/omock/model/player/BlackPlayer.kt
> +    }
원래는 두 함수의 기능이 같았으나, 의존성 분리를 위해서 수정하고 보니 같은 기능을 하고 있었군요.. 수정하였습니다

2024-03-27 06:16 UTC, jinuemong commented on src/main/kotlin/omock/model/position/Column.kt
> +        private const val MAX_COLUMN = 'O'
저는 Column의 책임이라고 봅니다.
사실상 입출력을 위해서 A~O의 범위를 지정하고 있으나,
확장성을 고려한다면 Column의 책임이라고 봤습니다.
실제로 Column에 저장하는 값이기도 하고, 추후에 데이터베이스까지 활용한다면 단순히 (1,1)로 저장하는 것보다 1A형식으로 저장하는 것이 저의 설계에 적합하다고 봤습니다..

2024-03-27 07:19 UTC, jinuemong commented on src/test/kotlin/omock/OmockRuleTest.kt
> +    }
오 이런건 몰랐는데 감사합니다 ! 배우고 가네요

2024-03-27 13:41 UTC, jinuemong commented
[3차 리팩토링]
OmokRule의 책임을 4가지로 분리해보았습니다.
전체적인 리팩토링 과정을 거쳐봤습니다 😭 대공사가 이루어졌군요..

질문이 있습니다!
추상화 된 인터페이스에 함수를 선언하고 구현하는 클래스에서 함수를 오버라이딩 하는 경우에,
해당 함수의 매개변수를 모두 쓰지 않는 경우가 발생했습니다.
예를 들어서 
A클래스 : override fun make(매개변수1, 매개변수2){return 매개변수 1}
C클래스 : override fun make(매개변수1, 매개변수2){return 매개변수 2 }
B클래스 : override fun make(매개변수1, 매개변수2){return 매개변수 1 + 매개변수 2}

세 함수의 기능이 동일하다고 했을때, 사용하지 않는 매개변수까지 넘겨주는게 문제가 있는지 궁금합니다.

2024-03-27 15:11 UTC, Gyuil-Hwnag approved these changes
누누 안녕하세요!
오목 미션 너무 고생 많으셨습니다! 
미션 구현과 리뷰 반영 정말 잘 해주셨네요💯
리뷰를 반영하면서 각 객체에 대한 책임 분리로 인하여 많은 수정이 있었던 것 같네요😅

해당 미션은 다음 미션 진행을 위하여 머지하도록 하겠습니다.
도움이 될만한 코멘트 달았으니 확인하여 다음 미션을 진행하기 전에 고민한 후에 반영을 해보면 좋을 것 같다는 생각이 듭니다!

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏
다음 미션도 화이팅입니다💪

2024-03-27 15:11 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/ruletype/RuleType.kt
> +sealed interface RuleType {
코멘트로 남겨주신, 인터페이스 함수에 대해서 사용을 안하는 파라미터들에 대한 내용인가 보군요!!
사용을 안하는 파라미터들까지 인터페이스 함수로 만들기보다는 각 객체에 맞게 객체 내부에서 함수로 만들어서 사용을 해보는 것은 어떨까라는 생각이 듭니다🤔
그렇게 하다보면 오히려 함수명들도 각 객체에 맞게 잘 변환을 하여 가독성 측면에서도 이점을 줄 수 있을 것 같다는 생각이 듭니다💪

2024-03-27 15:11 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/model/stone/Stone.kt
> +    val column: Column,
객체 지향 생활 체조 원칙에는 아래와 같은 규칙이 있는데, 해당 내용을 지키도록 설계를 해보는 것은 어떨까라는 생각이 듭니다!💪
- 게터/세터/프로퍼티를 쓰지 않는다.

2024-03-27 15:11 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/view/OutputView.kt
> +    private const val WHITE_STONE_NAME = "백"
고민해보면 좋을 내용인 것 같아서 코멘트 남겨두었습니다!🤔
Column 에서와 같은 고민을 한다면, 해당 내용은 Stone의 책임일까요?? View의 책임일까요??

2024-03-27 15:11 UTC, Gyuil-Hwnag commented on src/main/kotlin/omock/view/OutputView.kt
> +    private const val OUTPUT_GAME_START_MESSAGE = "오목 게임을 시작합니다."
상수화를 통해서 각 String에 대한 네이밍으로 의미를 부여해주셨네요~👍

2024-03-27 15:11 UTC, Gyuil-Hwnag commented on src/test/kotlin/omock/OmockRuleTest.kt
> +class OmockRuleTest {
OmockRule에 대한 테스트 코드 너무 잘 작성해주셨습니다!!
함수명들만 보고도 어떤 기능을 테스트 하는지 알 수 있군요~👍

2024-03-27 15:11 UTC, Gyuil-Hwnag commented on src/test/kotlin/omock/StoneTest.kt
> +    }
고민해보면 좋을 내용인 것 같아서 코멘트 남겨두었습니다!
재활용할 수 있다 라는 네이밍은 자칫 혼란을 일으킬 수도 있겠다는 생각이 듭니다🥲

2024-03-27 15:13 UTC, merged

2024-03-30 08:41 UTC, jinuemong commented on src/main/kotlin/omock/model/position/Row.kt
> +value class Row(val comma: String) {
value 클래스를 이번 미션에서 처음 사용해보았습니다.
하나의 프로퍼티를 가지며 성능이나 메모리에 좋다고 생각했습니다 !
@JvmInline 어노테이션을 활용하면 value class의 인스턴스가 실제 값으로 인라인 처리되도록 한다고 배웠습니다.
성능 최적화를 제공한다는데, 어느정도인지는 아직 모르겠어요
페어와 함께 사용한 의도는 타입 안전성과 성능의 이점을 활용(?)하자는 목적이 있었습니다