[오목] 꼬상 1, 2단계 미션 제출합니다.
woowacourse/kotlin-omok pull request #66
Opened 2024-03-21 08:12 UTC by kkosang

안녕하세요 말리빈 !
이번 오목 미션을 함께 하게된 안드로이드 6기 꼬상이라고 합니다
잘 부탁드립니다 🙇🏻‍♂️

2024-03-22 02:37 UTC, malibinYun requested changes
안녕하세요! 저도 잘 부탁드립니다 :)
1, 2단계 미션 고생 많으셨어요.
여러 고민해볼 점들 남겨두었으니 충분히 고민해보는 시간 가져보시면 좋겠어요!
피드백 반영 후 다시 리뷰 요청 부탁드려요.

2024-03-22 02:37 UTC, malibinYun commented on src/main/kotlin/omok/controller/OmokController.kt
> +    }
컨트롤러가 오목 게임 플레이에 대한 로직을 알고 있어보이네요!
오목 게임에 대한 로직을 최대한 도메인 로직으로 밀어 넣을 방법이 더 있을까요?

2024-03-22 02:37 UTC, malibinYun commented on src/main/kotlin/omok/model/Row.kt
> +            val rowValue = row.toIntOrNull()
문자열을 Row를 생성하기 위한 숫자로 바꾸는 일은 도메인의 역할일까요?

2024-03-22 02:37 UTC, malibinYun commented on src/main/kotlin/omok/model/Row.kt
> +            val rowValue = row.toIntOrNull()
또, 생성자를 활용하지 않은 이유가 궁금해요!

2024-03-22 02:37 UTC, malibinYun commented on src/main/kotlin/omok/model/Coordinate.kt
> +data class Coordinate(val row: Row, val col: Column)
Row와 Column 이름을 보고, 내부에는 여러 돌들이 들어있을 것 같은 느낌을 받았어요.
행과 열은 특정 하나를 가리키는 게 아니니,
좀 더 구체적인 이름으로 변경해보는 건 어떨까요?

2024-03-22 02:37 UTC, malibinYun commented on src/main/kotlin/omok/model/Board.kt
> +    }
금지된 수를 놓는 경우는 예외이고, 프로그램 오류일까요?

2024-03-22 02:37 UTC, malibinYun commented on src/main/kotlin/omok/model/RuleAdapter.kt
> +class RuleAdapter(stones: Stones) : Rule {
RuleAdapter는 인터페이스 인줄 알았는데, 구현체였네요!
인터페이스에 대해 구현한 내용을 구현체의 이름에 녹여내보는 건 어떨까요?

아래 예시를 들어볼게요!
```kotlin
interface NumberGenerator

class RandomNumberGenerator : NumberGenerator

class OddNumberGenerator : NumberGenerator

class RandomNegativeNumberGenerator : NumberGenerator
```

2024-03-22 02:37 UTC, malibinYun commented on src/main/kotlin/omok/model/RuleAdapter.kt
> +class RuleAdapter(stones: Stones) : Rule {
또, 판에 돌을 둘 때마다 이 객체를 매번 생성해야하는 건 비효율적이란 생각이 드네요.
한 번만 생성하고 재활용해보는 방법이 있을까요?

2024-03-22 02:37 UTC, malibinYun commented on src/main/kotlin/omok/model/Stones.kt
> +        dc: Int,
dr, dc는 다른 개발자가 보고도 한 번에 이해할 수 있는 단어일까요?
축약어의 사용을 지양해주세요 :)

2024-03-22 02:37 UTC, malibinYun commented on src/main/kotlin/omok/model/Stones.kt
> +            )
방향에 대해 객체로 표현해보는 건 어떨까요?

2024-03-22 02:37 UTC, malibinYun commented on src/test/kotlin/omok/model/StonesTest.kt
> +        stones.putStone(Stone(Color.BLACK, COORDINATE_F9))
Stones 객체를 생성할 떄 초기값을 넣을 수 있게 구성해보는 건 어떨까요?
또, 돌이 어떻게 놓여있는지 주석으로 표기한다면, 가독성을 훨씬 높여볼 수 있겠어요 :)

2024-03-23 02:10 UTC, kkosang commented on src/main/kotlin/omok/model/Row.kt
> +            val rowValue = row.toIntOrNull()
> 문자열을 Row를 생성하기 위한 숫자로 바꾸는 일은 도메인의 역할일까요?

 inputView에서는 입력 받은 값을 그대로 반환해주는 역할만 한다고 생각해서 Row 클래스에서 변경하도록 했습니다 !

2024-03-23 02:37 UTC, kkosang commented on src/main/kotlin/omok/model/Row.kt
> +            val rowValue = row.toIntOrNull()
> 또, 생성자를 활용하지 않은 이유가 궁금해요!

팩토리 메서드를 사용한 이유는 Row의 값이 Int타입을 가져야 하는데 입력값으로 String이 들어오기 때문에 숫자로 변환하는 과정이 필요하다고 생각해서 팩토리 메서드로 사용했습니다 ! 말씀해주신대로 숫자로 바꾸는 일을 view에서 작업하면 주 생성자로 사용 할 수 있을 것 같습니다 !

- Column 같은 경우에도 알파벳을 숫자로 변환해주는 로직을 view에서 하도록 하는게 좋을까요? 아니면 Column의 경우에는 도메인 로직에 해당해서 그대로 냅두는 것이 좋을까요 ?

2024-03-23 07:18 UTC, kkosang commented on src/test/kotlin/omok/model/StonesTest.kt
> +        stones.putStone(Stone(Color.BLACK, COORDINATE_F9))
> Stones 객체를 생성할 떄 초기값을 넣을 수 있게 구성해보는 건 어떨까요? 또, 돌이 어떻게 놓여있는지 주석으로 표기한다면, 가독성을 훨씬 높여볼 수 있겠어요 :)

피드백 주신 내용이, 테스트 코드를 위한 생성자를 만들도록 하신게 맞을까요? 제가 제대로 이해한 것인지 궁금합니다 !

2024-03-24 05:23 UTC, kkosang commented on src/main/kotlin/omok/model/Board.kt
> +    }
> 금지된 수를 놓는 경우는 예외이고, 프로그램 오류일까요?

프로그램의 오류가 아닌 사용자의 입력 오류로, 에러를 던지지않고 돌을 놓았는지 여부를 true/false로 반환하도록 수정하겠습니다 !

2024-03-24 09:44 UTC, kkosang commented
안녕하세요 말리빈 !
피드백 반영 하면서 말리빈의 의도와 다르게 반영이 되었다면 말씀해 주시면 감사하겠습니다 🙇🏻‍♂️

수정 사항은 🚀이모지를, 궁금증 및 질문사항이 있는 부분에는 코멘트를 달아놨습니다 !

2024-03-25 08:16 UTC, malibinYun requested changes
피드백 반영하시느라 고생 많으셨어요!
생각해볼만한 곳에 코멘트 남겨두었으니, 충분히 고민해보세요!
피드백 반영 후 다시 리뷰 요청 부탁드려요.

2024-03-25 08:16 UTC, malibinYun commented on src/main/kotlin/omok/model/Direction.kt
> +}
방향에 대해 enum으로 표현해보는 건 어떨까요?

2024-03-25 08:16 UTC, malibinYun commented on src/main/kotlin/omok/model/Board.kt
> +        return stones.putStone(stone)
Boolean이 어떤 의미를 뜻하는지 다른 개발자들도 한 번에 이해할 수 있을까요?

2024-03-25 08:16 UTC, malibinYun commented on src/main/kotlin/omok/model/OmokGame.kt
> +    private fun changeState() {
이 함수명만 보았을 때, 내부에서 어떤 일을 할 지 다른 동료들이 유추해낼 수 있을까요?

2024-03-25 08:16 UTC, malibinYun commented on src/main/kotlin/omok/model/PositionX.kt
> +}
좌표 자체가 15칸으로 제한되어있네요!
다른 여러 칸수의 오목판들을 선택할 수 있는 요구사항이 추가된다면, 유연하게 변경할 수 있을까요?
좌표에 오목 판의 칸 수의 제약을 갖는 것이 적절할지 고민해보시면 좋겠어요!

2024-03-25 08:16 UTC, malibinYun commented on src/main/kotlin/omok/model/PositionY.kt
> +data class PositionY private constructor(val value: Int) {
A,B,C... 는 View의 요소는 아닐지 고민해보시면 좋겠어요!

2024-03-25 08:16 UTC, malibinYun commented on src/main/kotlin/omok/model/State.kt
> +}
State 란 단어는 다른 개발자들도 한 번에 이해할 수 있는 단어일까요?

또, enum class와는 어떤 차이점이 있었나요?

2024-03-25 08:16 UTC, malibinYun commented on src/test/kotlin/omok/model/BoardTest.kt
> +     */
굉장히 열심히 만들어주셨네요 ㅎ_ㅎ 👍

2024-03-25 08:16 UTC, malibinYun commented on src/test/kotlin/omok/model/TestFixture.kt
> +    )
어떤 부분은 픽스처를 활용해주셨고, 어떤 부분은 테스트 코드에 직접 작성해주셨네요!
어떤 기준으로 이렇게 작성해주셨나요?_?

테스트 픽스처에 대한 좋은 글을 공유드랴요!
https://jojoldu.tistory.com/611

2024-03-27 13:01 UTC, kkosang commented on src/main/kotlin/omok/model/Board.kt
> +    private val rule: Rule = RenjuRule(stones)
> 룰에 대한 구현체를 변경하거나 다른 룰이 적용된 Board객체를 만들고 싶다면, 이 파일을 복사해서 새로 만들어야할까요? Board 객체를 룰의 구현체에 대해 유연하게 만들 수 있는 방법이 있을까요?

다른 룰이 적용된 Board 객체를 만들기 위해 Rule 을 의존성 주입을 통해서 생성할 수 있도록 수정하였습니다 !

2024-03-28 02:46 UTC, malibinYun approved these changes
피드백 반영하시느라 고생 많으셨어요!
다음 단계가 많이 어려울텐데 제가 여기에 너무 시간 끈 게 아닐까 하는 마음이 드네요 😅
그레도 객체 간 역할들이 잘 분리되어있어서 큰 무리 없이 구현할 수 있을 거란 생각이 들어요!
다음 미션도 화이팅입니다 💪

2024-03-28 02:46 UTC, malibinYun commented on src/main/kotlin/omok/model/Board.kt
> +    }
보드 객체가 무슨 일을 하는지 깔끔하게 보이네요! 👍
when 절을 활용해보셔도 좋겠어요 :)

2024-03-28 02:46 UTC, malibinYun commented on src/main/kotlin/omok/model/Coordinate.kt
> +data class Coordinate(val x: PositionX, val y: PositionY)
PositionX와 PositionY는 둘 다 int 라는 값을 가지고 있는데 클래스로 구분한 이유가 궁금해요!

2024-03-28 02:46 UTC, malibinYun commented on src/main/kotlin/omok/model/Direction.kt
> +enum class Direction(val x: Int, val y: Int) {
방향에 대해 객체로 표현해주셨네요!
값의 x,y 는 마치 좌표 같으니, 변화 값에 대한 정도를 나타내는 수학 용어인 dx, dy 정도로 변경해보는 건 어떨까요?

2024-03-28 02:46 UTC, malibinYun commented on src/main/kotlin/omok/model/Direction.kt
> +data class BiDirection(val direction1: Direction, val direction2: Direction)
가로 세로 양 대각에 대한 표현도 enum으로 표현해볼 수 있어 보이네요!

2024-03-28 02:46 UTC, malibinYun commented on src/main/kotlin/omok/model/OmokGame.kt
Controller가 가지고 있는 역할을 좀 더 이곳으로 옮길 수 있어보이네요!

2024-03-28 02:46 UTC, malibinYun commented on src/main/kotlin/omok/model/RuleAdaptor.kt
룰 객체를 매번 만드는 건 비효율이니, 한 개만 만들 수 없는지에 대한 질문이 많이 어려우셨나보네요!
사실, 고민해서 자신만의 답변을 해주시기를 기대했어요.

라이브러리의 RenjuRule 객체 때문에서라도, 매번 객체를 만들 수 밖에 없는 구조였거든요.
라이브러리의 수정을 해서 한 개만 만들 수 있게 변경해볼지, 혹은 그렇지 않고 객체를 매번 만들지에 대한 선택을 어떤 고민을 통해 하게 되었는지를 고민하게 만드는 것이 의도였어요.
라이브러리를 선택하는 자신만의 기준을 세울 수도 있는 좋은 고민이란 생각이 들어서요 :)

개인적으로는, 라이브러리를 수정할 수 있는 형태이니, 저라면 라이브러리를 뜯어고쳤거나,
객체를 1개만 만들어서 재활용할 수 있는 형태의 라이브러리를 다시 찾아보았을 것 같네요!

2024-03-28 02:46 UTC, malibinYun commented on src/main/kotlin/omok/model/RuleAdaptor.kt
> +class RuleAdaptor(private val stones: Stones) : Rule {
다른 룰 구현체가 생겨나게 된다면, 그 이름은 RuleAdaptor2가 되는 게 자연스러울까요?
Adaptor라는 말은 어떤 룰인지에 대해 알기는 어려워보이네요! 적절한 단어가 있을까요?

2024-03-28 02:46 UTC, malibinYun commented on src/main/kotlin/omok/model/RuleAdaptor.kt
> +    fun checkInvalid(stone: Stone): Boolean {
이 메서드는 어떤 이유에서 공개되어있는걸까요 ?_?

2024-03-28 02:46 UTC, malibinYun commented on src/main/kotlin/omok/model/RuleAdaptor.kt
> +        return 2
매직 넘버를 상수화해서 1과 2는 어떤 값인지 의미를 부여해보는 건 어떨까요?

2024-03-28 02:46 UTC, malibinYun commented on src/main/kotlin/omok/model/Stone.kt
> +data class Stone(val color: Color, val coordinate: Coordinate)
돌 스스로가 좌표를 갖는 것은 자연스러울지 고민해보시면 좋겠어요!

2024-03-28 02:46 UTC, malibinYun commented on src/main/kotlin/omok/model/StoneState.kt
> +    data object SuccessfulPlaced : StoneState()
하위 구현체 중 SuccessfulPlaced는 message를 필요로 하지 않네요.
모든 하위 구현체가 message를 갖게한 특별한 이유가 있을까요?

2024-03-28 02:46 UTC, malibinYun commented on src/test/kotlin/omok/model/TestFixture.kt
> +    )
`COORDINATE_~` 요 부분은 좋은 픽스처라고 생각해요.
아래에 돌이 놓인 케이스에 대해 질문 드린거였어요!

돌이 놓인 곳들에 대해 테스트에 직접 작성해주신 부분들이 있는데, 어떤 테스트는 여기에 있는 픽스처를 활용하고 있어서요. 

`beforeEach를 사용해야 하는 경우가 있을까요??`이 질문에 답은 `beforeEach (setup) 등 사용할 경우 테스트 코드가 강하게 결합되어서 사용을 지양해야 한다고 이해` 여기에 답이 들어있네요!
테스트 코드 끼리 강하게 결합되지 않는 경우에 활용해요.

저는 주로 각 테스트가 필요한 초기 상태의 객체를 만들 때 사용해요.
특히 객체의 상태가 존재하지 않는다면 테스트간 결합이 발생할 이유가 없으니, BeforeEach가 아닌 필드에 바로 생성을 선언하기도 해요.

2024-03-28 02:46 UTC, merged

2024-03-28 02:50 UTC, malibinYun commented on src/main/kotlin/omok/model/Row.kt
> +            val rowValue = row.toIntOrNull()
어디까지가 도메인의 범위일지 스스로의 결정이 필요한 시점으로 보여요.
알파뱃이 정말 좌표로써 중요한 도메인이라면 도메인으로 분류하는 것이 좋겠고,
알파뱃도 결국 숫자 좌표로 변환될 수 있으며, 보여줄 때만 알파뱃이지 본질은 좌표와 다르지 않다고 생각한다면 도메인으로 분류하지 않는 것이 좋겠지요.

저는 후자의 의견이 강해요 :)
바둑을 두던 사람이라면 G8이 어느 좌표인지 머릿속으로 떠올릴 수 있겠지만,
바둑을 모르는 개발자가 인수인계 받는다면, G8이란 좌표가 어디인지 떠올리는 데 시간이 걸리겠지요!
개발에서까지 알파뱃 좌표를 넣는 것이 정말 유효한지 저는 의심이 많이 되어요. 좌표 값은 본질적으로 숫자라고 생각해서요.

2024-03-28 02:52 UTC, malibinYun commented on src/test/kotlin/omok/model/StonesTest.kt
> +        stones.putStone(Stone(Color.BLACK, COORDINATE_F9))
`테스트 코드를 위한` 생성자를 만들라는 것은 의도에 맞지 않아요.
해당 객체를 만들 때 초기값을 넣을 수 있게 하는 건, 객체의 유연함을 더하고 부가적으로 테스트를 쉽게 작성할 수 있게 되는것이지, 테스트만을 위한 것이 아닙니다.

2024-04-01 06:51 UTC, kkosang commented on src/main/kotlin/omok/model/Coordinate.kt
> +data class Coordinate(val x: PositionX, val y: PositionY)
> PositionX와 PositionY는 둘 다 int 라는 값을 가지고 있는데 클래스로 구분한 이유가 궁금해요!

기존의 코드에서 PositionX,Y에서 검증을 하여서 Coordinate는 검증된 값만 들어올 수 있다는 걸 표현하고 싶었습니다 !
현재 코드는 board에서 좌표의 값을 검증하기 때문에 Coordinate에서 원시값 포장을 하지 않아도 괜찮다고 생각합니다.
수정하도록 하겠습니다 !

2024-04-01 07:15 UTC, kkosang commented on src/main/kotlin/omok/model/StoneState.kt
> +    data object SuccessfulPlaced : StoneState()
> 하위 구현체 중 SuccessfulPlaced는 message를 필요로 하지 않네요. 모든 하위 구현체가 message를 갖게한 특별한 이유가 있을까요?

성공했을 때도 확장성을 고려하여 StoneState에서 message를 갖도록 구현했었는데 불필요한 것 같아서 수정하였습니다 !

2024-04-01 07:24 UTC, kkosang commented on src/main/kotlin/omok/model/RuleAdaptor.kt
> +    fun checkInvalid(stone: Stone): Boolean {
> 이 메서드는 어떤 이유에서 공개되어있는걸까요 ?_?

내부에서만 사용하고 있는데, 깜빡하고 private로 설정 못했습니다..!

2024-04-01 07:25 UTC, kkosang commented on src/main/kotlin/omok/model/RuleAdaptor.kt
> +class RuleAdaptor(private val stones: Stones) : Rule {
> 다른 룰 구현체가 생겨나게 된다면, 그 이름은 RuleAdaptor2가 되는 게 자연스러울까요? Adaptor라는 말은 어떤 룰인지에 대해 알기는 어려워보이네요! 적절한 단어가 있을까요?

인터페이스에 대한 구현체 네이밍 방식을 따라 RenjuRule로 수정하였습니다 !

2024-04-01 07:40 UTC, kkosang commented on src/main/kotlin/omok/model/RuleAdaptor.kt
> 룰 객체를 매번 만드는 건 비효율이니, 한 개만 만들 수 없는지에 대한 질문이 많이 어려우셨나보네요! 사실, 고민해서 자신만의 답변을 해주시기를 기대했어요.
> 
> 라이브러리의 RenjuRule 객체 때문에서라도, 매번 객체를 만들 수 밖에 없는 구조였거든요. 라이브러리의 수정을 해서 한 개만 만들 수 있게 변경해볼지, 혹은 그렇지 않고 객체를 매번 만들지에 대한 선택을 어떤 고민을 통해 하게 되었는지를 고민하게 만드는 것이 의도였어요. 라이브러리를 선택하는 자신만의 기준을 세울 수도 있는 좋은 고민이란 생각이 들어서요 :)
> 
> 개인적으로는, 라이브러리를 수정할 수 있는 형태이니, 저라면 라이브러리를 뜯어고쳤거나, 객체를 1개만 만들어서 재활용할 수 있는 형태의 라이브러리를 다시 찾아보았을 것 같네요!

라이브러리를 온전히 이해하고 사용한 것이 아니라서 라이브러리를 수정하는데 어려움이 있었습니다..!
앞으로 라이브러리를 사용할 때는 구조를 온전히 이해하고 수정할 수 있는 부분이 있다면 수정해서 사용하도록 하겠습니다 !