[오목] 예니 1,2단계 미션 제출합니다.
woowacourse/kotlin-omok pull request #73
Opened 2024-03-21 08:33 UTC by JoYehyun99

잘 부탁드립니다!

2024-03-22 05:49 UTC, KwonDae requested changes
안녕하세요 예니.

오목 미션 진행하는 동안 잘 부탁드립니다.
1,2단계 잘 구현 해주셨습니다 👍 

주로 객체 간의 관계, 구조적인 면을 집중적으로 코멘트를 남겨드렸습니다.
천천히 고민해보시고 확인 후 다시 요청 부탁드립니다!

2024-03-22 05:49 UTC, KwonDae commented on src/main/kotlin/omok/model/RenjuRule.kt
> +package omok.model
오목 규칙은 별도 패키지로 분리해보는건 어떨까요?

2024-03-22 05:49 UTC, KwonDae commented on src/main/kotlin/omok/model/Turn.kt
> +}
Interface 활용 👍

2024-03-22 05:49 UTC, KwonDae commented on src/main/kotlin/omok/model/Rule.kt
> +    }
예니의 의견이 궁금한 부분인데요,
플레이어의 승리조건에 대한 로직은 Rule에 해당하는 걸까요?
```kotlin
override fun checkCount(count: Int): Boolean = count == Rule.WINNING_COUNT
```

BlackRule, WhiteRule 모두 위의 중복된 로직을 갖게 되는데
오목의 승리조건은 공통 조건이지만, 각 BlackRule, WhiteRule 하위에 따로 override 되어있다면 각자 다른 조건을 갖고 있나? 라고 생각할 수 있을 것 같아요.

2024-03-22 05:49 UTC, KwonDae commented on src/main/kotlin/omok/model/Rule.kt
> +}
렌주룰의 경우 흑,백에 따라서 다르게 동작하는게 아닌 Board에 따라서 판단을 하는데 
현재 Black, White에 엮여서 승리조건이랑 함께 엮여있는게 어색하다는 생각이 듭니다.
룰은 Black 이라는 키워드에 의존적인게 아닌 룰 자체니까요..!

2024-03-25 07:25 UTC, JoYehyun99 commented on src/main/kotlin/omok/controller/Controller.kt
> +        }
`OmokGame` 클래스를 생성해서 게임 진행 로직을 담았습니다!

2024-03-25 14:52 UTC, JoYehyun99 commented on src/main/kotlin/omok/model/Rule.kt
> +    fun checkDirection(
stone 개수를 count한다는 의미를 담도록 수정하겠습니다!

2024-03-25 15:15 UTC, JoYehyun99 commented on src/main/kotlin/omok/model/Rule.kt
> +    }
승리 판단 기능 또한 rule이 될 수 있다고 생각했었던 것 같습니다..! 
BlackRule, WhiteRule로 나눴던 이유는 렌주룰 적용하는 과정에서 나뉘는 부분이 있다고 헷갈렸던 것 같습니다 🥹
승리 판단 로직은 `Board`에서 하도록 수정하겠습니다!

2024-03-25 15:16 UTC, JoYehyun99 commented on src/main/kotlin/omok/model/Rule.kt
> +}
승리 판단 로직은 `Board`에서 하도록 수정하겠습니다!

2024-03-26 11:45 UTC, KwonDae requested changes
피드백 반영을 정말 잘해주셨습니다 👍 
3,4 단계로 넘어가기 전 한가지는 살펴보고 넘어가면 좋을 것 같아 코멘트를 남겼습니다.
진행하면서 논의 사항이 있다면 언제든 편하게 DM 주세요 :) 
확인 부탁드립니다~!

2024-03-26 11:45 UTC, KwonDae commented on src/main/kotlin/omok/controller/Controller.kt
> -        private const val MESSAGE_INVALID_POINT_INPUT = "해당 위치 좌표에 이미 돌이 착수되어 있습니다. 다시 입력해주세요."
wow..😮

2024-03-26 11:45 UTC, KwonDae commented on src/main/kotlin/omok/model/OmokGame.kt
> +    ) {
람다 활용 👍

2024-03-26 11:45 UTC, KwonDae commented on src/main/kotlin/omok/model/RenjuRuleAdaptor.kt
> +object RenjuRuleAdaptor {
힌트를 드리지 않았음에도 어댑터를 활용해주셨네요! 👍

2024-03-26 11:45 UTC, KwonDae commented on src/main/kotlin/omok/model/RenjuRuleAdaptor.kt
> +        }
rule은 사실 어댑터 인스턴스가 생성될 때 이미 정해져있지 않을까요?
```suggestion
class RenjuRuleAdapter(rule: OmokRule) {
    ....
    fun isForbidden(...): Boolean {
        return  rule.validPosition(board, point.x, point.y)
     }
}
        
```

2024-03-26 11:45 UTC, KwonDae commented on src/main/kotlin/omok/rule/RenjuRule.kt
> +class RenjuRule(
룰이 라이브러리처럼 도메인에 의존하지 않게끔 잘 구현해주셨네요 👍

2024-03-26 11:45 UTC, KwonDae commented on src/main/kotlin/omok/controller/Controller.kt
> +        OmokGame().play(OutputView::printBoard, OutputView::printTurn, ::getPoint)
[Function reference](https://kotlinlang.org/docs/reflection.html#function-references)는 람다함수와 어떤 차이점이 있을까요?

2024-03-26 15:44 UTC, JoYehyun99 commented on src/main/kotlin/omok/controller/Controller.kt
> +        OmokGame().play(OutputView::printBoard, OutputView::printTurn, ::getPoint)
기존에 정의된 메서드들을 단순히 호출하는 경우,
함수 참조는  람다식에서 불필요한 매개변수를 제거할 수 있다는 점에서 가독성이 좋은 것 같습니다..!

2024-03-26 21:52 UTC, KwonDae commented on src/main/kotlin/omok/controller/Controller.kt
> +        OmokGame().play(OutputView::printBoard, OutputView::printTurn, ::getPoint)
또한, 참조를 하게되면 KProperty 개념이 등장하는데요 이부분도 함께 찾아보시면 도움이 될 것 같습니다.

2024-03-26 22:02 UTC, KwonDae approved these changes
피드백 반영을 잘 해주셨습니다.
리펙토링 과정에서 렌주룰을 어떻게 애플리케이션에서 다루어야 하는지 방향을 잘 이해하고 구현해주셔서 좋았습니다 👍 

3,4 단계로 넘어가면서 집중해야 할 포인트는 현재 구조를 많은 수정 없이 안드로이드에 적용할 수 있는가? 입니다.

별다른 수정없이 안드로이드에 이식이 가능하다면 좋겠지만, 과정에서 피할 수 없는 수정들이 있을텐데요 지금은 안드로이드에 적용해보면서 어떤 과정들이 있는지 경험해보는 것이 중요하기에 이부분을 고민해보시면 좋겠습니다.

피드백 반영 고생 많으셨습니다. 안드로이드에서 다시 뵙겠습니다 :)

2024-03-26 22:02 UTC, merged