[오목] 채드 1,2단계 미션 제출합니다.
woowacourse/kotlin-omok pull request #74
Opened 2024-03-21 08:35 UTC by dpcks0509

안녕하세요 안드로이드 6기 채드입니다!
리뷰 잘 부탁드립니다!!

2024-03-21 11:23 UTC, laco-dev commented on src/main/kotlin/omok/controller/Controller.kt
> +        private const val MESSAGE_INVALID_POINT_INPUT = "해당 위치 좌표에 이미 돌이 착수되어 있습니다. 다시 입력해주세요."
이 내용은, 만약 게임을 하고 있다면  사용자에게 안내해야 하는 메시지죠?
그렇다면 컨트롤러에서 출력하는게 맞을까요?

2024-03-21 11:24 UTC, laco-dev commented on src/main/kotlin/omok/controller/Controller.kt
> +        }
1. Board에 돌을 놓는다
2. Turn에 돌을 놓는다.

객체의 역할 중 무엇이 적절하다고 생각하시나요?
게임이 흘러가는 판을 가장 잘 알고 있는건 보드일까? 턴 일까? 🤔

2024-03-21 11:26 UTC, laco-dev commented on src/main/kotlin/omok/model/Board.kt
> +        }
이중 배열의 구조가 x, y 좌표에 접근하는 개념에 적합한 자료구조일까요?

2024-03-21 13:09 UTC, laco-dev commented on README.md
> +    - 동시에 두 개의 '3'이 발생하여 상대편이 한 쪽을 막아도 다른 쪽으로 '열린 4'를 만들 수 있는 지점을 의미한다.
이거는 제가 잘못 이해를 하고 있었네요..
가운데 놓으려고 하니까 블록을 당하는군요

2024-03-22 05:16 UTC, dpcks0509 commented on src/main/kotlin/omok/model/RenjuRule.kt
> +object RenjuRule {
Rule, RenjuRule, Direction 클래스를 rule 이라는 패키지로 따로 분리하였습니다!

2024-03-22 17:00 UTC, dpcks0509 commented on src/main/kotlin/omok/controller/Controller.kt
> +        private const val MESSAGE_INVALID_POINT_INPUT = "해당 위치 좌표에 이미 돌이 착수되어 있습니다. 다시 입력해주세요."
OutputView에서 처리하도록 수정했습니다!

2024-03-22 17:52 UTC, dpcks0509 commented on src/main/kotlin/omok/controller/Controller.kt
> +        }
Board에 돌을 놓도록 로직 수정하였습니다!
그런데 원래는 putStone 로직의 인자로 Stone(stoneType, point)이렇게 넘겨 줬는데 stoneType에 대한 정보를 알수가 없어서 point로만 넘겨주는 방식으로 변경하였더니, 테스트 코드에서 BLACK 돌만 임의적으로 넣어줄 수 없게 되어서 test 코드에서 BLACK,WHITE 돌을 한개씩 번갈아서 입력해야해 putStone을 호출하는 횟수가 2배로 증가하였는데 이러한 것은 상관이 없는걸까요? 어떻게 처리해야할지 의문이 들어 질문을 드립니다!

2024-03-22 17:56 UTC, dpcks0509 commented on src/main/kotlin/omok/model/Board.kt
> +        }
이중배열을 MutableList보다는 Array로 처리하는게 더 적합하다고 생각하여 수정하였습니다!

2024-03-22 18:10 UTC, dpcks0509 commented on src/main/kotlin/omok/model/Point.kt
> +        private const val MESSAGE_INVALID_POINT_INPUT = "잘못된 위치 좌표입니다. 재입력 해주세요."
OutputView에서 처리하도록 수정했습니다!

2024-03-22 18:24 UTC, dpcks0509 commented on src/main/kotlin/omok/view/OutputView.kt
> +    }
필요한 보드의 값을 보드에서 get함수를 통해 가져오도록 수정하였습니다!

2024-03-23 00:08 UTC, laco-dev requested changes
피드백 반영 고생하셨습니다.

오목게임은 항상 15x15에서만 진행 한다는 사실에 강하게 결합되어 있는 것 같습니다.
오목 게임이 20x20이 되는순간 프로그램에 대참사가 벌어질 것 같아요.

그 외에 고민이 다소 필요할 내용들이 있어, 몇가지 의견 남겨드렸습니다.

2024-03-23 00:08 UTC, laco-dev commented on src/main/kotlin/omok/view/OutputView.kt
> +        )
이미 OutputView가 보드는 무조건 15크기로만 만들어져야 한다. 가 결정되어있네요.
미리 출력 포맷을 15크기로 결정해 두는 것에 대한 생각을 듣고 싶습니다.

2024-03-23 00:08 UTC, laco-dev commented on src/test/kotlin/omok/model/rule/RenjuRuleTest.kt
> +package omok.model.rule
model.rule 패키지가 맞을까요?

라이브러리가 잘 동작하는지 테스트 하고 싶은 것일까요?
직접 구현한 어댑터가 잘 동작하는지 테스트 하고 싶은 것일까요?

2024-03-23 07:38 UTC, dpcks0509 commented on src/test/kotlin/omok/model/rule/RenjuRuleTest.kt
> +package omok.model.rule
처음에 패키지 설정이 잘못되어있었던 것 같습니다. 따로 model, rule 패키지 두개로 별도 분리하였습니다!

2024-03-23 07:55 UTC, dpcks0509 commented on src/main/kotlin/omok/model/Board.kt
> +    private var _turn: Turn = BlackTurn()
_turn을 삭제하고 turn을 var로 선언한 후 private set을 이용하는 방식으로 수정하였습니다!

2024-03-23 13:35 UTC, dpcks0509 commented on src/main/kotlin/omok/model/Board.kt
> +        get() = _table
외부에서 접근이 불가능하도록 수정하였습니다!

2024-03-23 13:50 UTC, dpcks0509 commented on src/main/kotlin/omok/model/Turn.kt
> +        if (BlackRule.isForbidden(board, stone)) return this
돌을 잘못 두었을 때 오류 메시지를 출력하여 사용자에게 알려구조, 재입력을 받고 있습니다. 그래서 재입력을 받기 위해 자기 자신의 턴을 반환하고 있습니다.

2024-03-23 14:08 UTC, dpcks0509 commented on src/main/kotlin/omok/model/Point.kt
> +    }
Board에 상수처리되어있는 BOARD_SIZE를 public으로 변경하고 Point의 MAX_POINT 대신 Board.BOARD_SIZE를 가져와서 보드의 사이즈가 변경되면 포인트의 최대값 또한 자동으로 변경되게 수정하였습니다!

2024-03-23 17:00 UTC, dpcks0509 commented on src/main/kotlin/omok/model/Turn.kt
> +    val before: Stone?
이전 돌의 위치를 가지고 있는 클래스를 Turn에서 Board가 가지고 있도록 교체하였습니다!

2024-03-24 15:40 UTC, dpcks0509 commented on src/main/kotlin/omok/rule/Rule.kt
> +import omok.model.StoneType
RenjuRule을 library 패키지로 별도로 선언하였고 model을 참조할 수 없도록 수정하였습니다!

2024-03-24 15:41 UTC, dpcks0509 commented on src/main/kotlin/omok/model/Board.kt
> +        }
파일 전역에서 BOARD_SIZE = 15를 공유하게 하여 BOARD_SIZE가 20으로 바뀌게 되면 라이브러리도 BOARD_SIZE = 20에 맞게 지원하도록 수정하였습니다!

2024-03-24 15:51 UTC, dpcks0509 commented on src/main/kotlin/omok/model/Turn.kt
> +        if (BlackRule.isForbidden(board, stone)) return this
RuleAdapter를 이용하여 BlackTurn, WhiteTurn에 따라 각각 다른 Rule이 적용되게 수정하였습니다!

2024-03-24 17:51 UTC, dpcks0509 commented on src/main/kotlin/omok/view/OutputView.kt
> +        )
하드코딩 된 부분을 함수를 통해서 보드 사이즈에 맞게 boardForm과 boardTable이 초기화되게 수정하였습니다!

2024-03-25 11:25 UTC, laco-dev approved these changes
도메인적인 확장성 보다는 어떻게 해야 콘솔에 잘 찍을 수 있을지를 고민한 것 같군요.. 😅 

추상 클래스를 지난 블랙잭 미션에서 충분히 이해하지 못한 부분이 있어요.
인터페이스와 추상 클래스에 대한 근본적인 차이도 다시 학습 해보시면 좋겠습니다.

이와 별개로 안드로이드 적용에 충분한 시간을 드리기 위해 1, 2단계 미션은 종료하도록 하겠습니다.
남겨드린 내용은 다음 단계 수행하면서 반영 해 주시고 지금의 구조가 안드로이드에서도 과연 좋은 설계로 적용할 수 있을지를 생각해보시면서 구현 해보시면 좋겠습니다.

2024-03-25 11:25 UTC, laco-dev commented on src/main/kotlin/omok/model/RuleAdapter.kt
> +}
렌주룰에 돌의 종류를 같이 전달하고 있는데, 블랙룰과 화이트룰이 나눠진 이유가 무엇인가요?
블랙턴에 화이트 룰을 적용할 경우를 기대하시는것일까요?

룰 어댑터가 인터페이스로 만들어진 이점을 잘 모르겠습니다

2024-03-25 11:25 UTC, laco-dev commented on src/main/kotlin/omok/model/RuleAdapter.kt
> +    }
추가로 인터페이스에 기본 구현 사용은 지양 해주세요.
인터페이스의 역할은 공통 로직을 구현하는 것이 아닌 역할을 정의하는 것입니다.

추상 클래스와 인터페이스의 차이는 무엇인가요?

2024-03-25 11:25 UTC, laco-dev commented on src/main/kotlin/omok/controller/Controller.kt
> +            }
> 돌을 잘못 두었을 때 오류 메시지를 출력하여 사용자에게 알려구조, 재입력을 받고 있습니다. 그래서 재입력을 받기 위해 자기 자신의 턴을 반환하고 있습니다.

돌을 잘못 두는게 오류인가요?
만약 휴대폰 번호를 입력하는데 11자리보다 길게 입력한다면 이건 오류인가요?

2024-03-25 11:25 UTC, laco-dev commented on src/main/kotlin/omok/model/Board.kt
> +        }
> 이중배열을 MutableList보다는 Array로 처리하는게 더 적합하다고 생각하여 수정하였습니다!
> 외부에서 접근이 불가능하도록 수정하였습니다!

다시 List로 돌아가는 이유가, 외부에서 접근이 불가능하도록 하기 위함이라면 잘못된 해결 방법입니다.

외부에서 접근이 불가능하도록 막는 방법이 단순히 자료구조로 결정되는 것이었다면 `getPointStoneLines()` 함수는 필요하지 않았습니다.

힌트는 table을 private으로 만드는 것입니다.

2024-03-25 11:25 UTC, laco-dev commented on src/main/kotlin/omok/model/Board.kt
> +    private var _beforePoint: Point? = null
backing property를 사용하는 케이스가 아닙니다.

아래 문서에서 적절한 구현 방법을 찾아보세요
https://kotlinlang.org/docs/properties.html#getters-and-setters

2024-03-25 11:25 UTC, laco-dev commented on src/test/kotlin/omok/model/RuleAdapterTest.kt
> +        board.putStone(Point(10, 0), WhiteTurn(WhiteRule()))
턴이 룰을 가지고 있게 하다보니, 턴마다 다른 룰을 적용할수도 있겠네? 라는 생각도 들었습니다.
```kotlin
WhiteTurn(BlackRule())
WhiteTurn(WhiteRule())
BlackTurn(WhiteRule())
WhiteTurn(MyRule())
...
```

룰이라는게 보드에 적용되는 개념인지, 플레이어마다 적용되는 개념인지를 다시 한번 묻고 싶네요
턴이 혹시나 너무 많은 일을 하려고 하다보니 어렵게 느껴졌을까요?

```kotlin
// Board
fun putStone(point: Point) {
   when {
      "이미 돌이 놓여져 있으면" -> { ... }
      "룰을 어겼으면" -> { ... }
      "정상" -> { table.put(...) }
   }
   turn = turn.next()
   if (isFinished()) { ... }
}
```

2024-03-25 11:25 UTC, merged

2024-03-25 17:26 UTC, dpcks0509 commented on src/main/kotlin/omok/controller/Controller.kt
> +            }
오류를 발생하는 대신 재입력해달라는 문구를 출력하고, 재입력을 받도록 수정하였습니다!

2024-03-25 17:51 UTC, dpcks0509 commented on src/main/kotlin/omok/model/Board.kt
> +    }
보드의 크기가 상수처리 되어있던 것을 삭제하고 Board 클래스 생성자에 size를 추가하여 보드의 크기가 유연하게 결정되도록 수정하였습니다!

2024-03-25 18:24 UTC, dpcks0509 commented on src/main/kotlin/omok/model/Board.kt
> +        }
backing property를 삭제하고 table을 private으로 선언하여 외부에서 수정을 할 수 없게 하였고, x와 y를 인자로 받는 getBoardPoint를 추가하여 table[y][x]에 저장된 값을 외부에서 확인할 수 있도록 수정하였습니다!

2024-03-25 18:28 UTC, dpcks0509 commented on src/main/kotlin/omok/model/Board.kt
> +    private var _beforePoint: Point? = null
backing property를 삭제하고 private set을 통해 커스텀 세터를 사용하도록 수정하였습니다!

2024-03-26 06:11 UTC, dpcks0509 commented on src/main/kotlin/omok/model/Turn.kt
> +        return BlackTurn(BlackRule())
sealed class로 선언하여 공통 함수로 한번에 처리가능하게 수정하였습니다!

2024-03-26 06:14 UTC, dpcks0509 commented on src/main/kotlin/omok/model/Turn.kt
> +        if (ruleAdapter.checkWin(board, stone)) return FinishedTurn(stoneType)
Turn에서는 BlackTurn, WhiteTurn 상관없이 동일하게 룰 검사를 진행하고 RuleAdapter에서 돌의 색깔에 따라 다른 룰이 적용되게 수정하였습니다!

2024-03-26 06:16 UTC, dpcks0509 commented on src/main/kotlin/omok/model/RuleAdapter.kt
> +}
RuleAdapter를 class로 수정하고 공통 로직을 통합시켰습니다!

2024-03-26 06:19 UTC, dpcks0509 commented on src/main/kotlin/omok/model/RuleAdapter.kt
> +    }
추상 클래스는 비슷한 클래스들을 묶어 공통 로직을 추상화 하는 클래스라고 생각했고,
다른 클래스들이라도 동일한 행동을 하는 공통 로직을 묶는 것을 인터페이스라고 생각했습니다.
그래서 추상 클래스로 변경하려다가 BlackRule, WhiteRule을 따로 나누지 않고 하나의 class로 묶을 수 있어 일반 class로 RuleAdapter를 선언하였습니다!

2024-03-26 06:45 UTC, dpcks0509 commented on src/test/kotlin/omok/model/RuleAdapterTest.kt
> +        board.putStone(Point(10, 0), WhiteTurn(WhiteRule()))
Turn에서 Rule을 의존하지 않도록 수정하였습니다!