[코비] 1, 2단계 오목 제출합니다.
woowacourse/kotlin-omok pull request #8
Opened 2023-03-16 08:03 UTC by rhkrwngud445

2023-03-16 23:07 UTC, namjackson commented
현재는 도메인 코드내의 의존성과 책임이 서로 얽혀있는 부분이 있는거 같아요!
먼저, 각 클래스의 책임에 대해 고민해보아요! ( 불필요하다면 과감히 제거해보아요! )
간단하게라도, 클래스 다이어그램을 그려보는것도 도움이 될거같아요 
혹시 막히는 부분이 있으면, 코멘트나 DM으로 편하게 질문 주세요!

2023-03-16 23:09 UTC, namjackson requested changes
안녕하세요 코비! 
오목 미션을 함께하게된 잭슨이라고 합니다! 
어려운 오목미션 구현을 잘해주셨네요!  💯 
몇가지 피드백을 코멘트로 남겼으니, 확인해주세요 👍

2023-03-17 07:25 UTC, rhkrwngud445 commented on src/main/kotlin/domain/Coordinate.kt
> +data class Coordinate private constructor(val point: Point) {
Coordinate는 오목판 위에 있는 돌의 좌표로 정의하였고, Point는 오목판을 넘어서 모든 범위의 좌표로 정의하였습니다!

오목판위의 범위의 좌표로 해당 범위가 아닌 값을 null로 처리하기 `Coordinate.from`는 nullable하게 정의하였습니다! 
다만 렌주 알고리즘을 적용하면서 plus 연산자를 통해 오목판 밖의 좌표를 다루게 되었고, 이 좌표값은 Coordinate로 정의하기 어렵게 되어 Point를 따로 두었습니다!

혹시 다른 방안이 있으면 피드백 부탁드리겠습니다!

2023-03-19 16:12 UTC, rhkrwngud445 commented
피드백 감사드립니다!
피드백을 반영하면서 전체적으로 Players, Player의 필요성을 찾지 못해 클래스를 지우고 Stones, Board에 위임이 될 수 있게 변경하였습니다!

Adapter 패턴과 Mapper interface도 적용시켜 보았는데, 적용한 경험이 부족해 리뷰어님이 주신 방향성과 맞는지에 스스로 확신이 서지 않았습니다😥
추가적으로 고쳐야 할 부분이 있다면 편하게 말씀주세요! 
바쁘신 와중에 다시 한 번 감사드립니다!

2023-03-20 14:10 UTC, namjackson approved these changes
안녕하세요 코비!
리뷰가 살짝 늦었네요! 피드백 적용 잘해주셨네요, 👍 
고민할법한 내용과 추가적인 코멘트를 남겼으니, 확인해주세요! 
변경사항은 다음미션 진행하면서 함께 수정해주세요! 🏃

2023-03-20 14:10 UTC, namjackson commented on src/main/kotlin/domain/Stones.kt
> +    }
같은 위치에 이미 돌이 있습니다.는 에러를 발생하고,
룰 위반의 경우에는 Boolean을 통해 사전에 검증을 하고 있네요,

에러 핸들링이 빠져있기도하고, 일관성있게 통일해보면 어떨까요?
Board클래스에서  Stones 의 validateRenju를 확인을하고, Stones 의 place가 실행이되네요.
Stones에게 메세지를 던져서 위임하고, 결과값 (성공, 실패)에 대한 값을 받아와서 처리해보면 어떨까요?

2023-03-20 14:10 UTC, namjackson commented on src/main/kotlin/domain/Stones.kt
> +    val renjuRuleAdapter = RenjuRuleAdapter(this)
추상화된다면, RuleAdapter에서는 "룰 위반으로 둘수있는 수인지" 만 관심사가 아닐까요?
실제로 어떤 룰을 따를지는 구현체에서 정의해보시면 어떨까요?

2023-03-20 14:11 UTC, merged