[오목] 팡태 3, 4단계 미션 제출합니다.
woowacourse/kotlin-omok pull request #88
Opened 2024-03-30 18:32 UTC by Hevton

안녕하세요 페로로! 팡태입니다.
저번 1, 2차 미션에서도 그렇고, 대면해서도 소중한 시간 내어주셔서 정말 감사합니다 ☺️

이전 미션에서 걱정해주셨던 것처럼,, 안드로이드로 옮기며 바꿔야만 했던 부분들이 있었고
1차에서 반영하지 못했던 부분들 또한 공부하여 반영했습니다.

리뷰에 어려움이 있으실까 하여 3가지로 넘버링 하겠습니다!

### 기존 1,2차 로직에서 변경된 점

1. 언급해주셨던 [Position이 View와 너무 강하게 결합되어 있다](https://github.com/woowacourse/kotlin-omok/pull/57#discussion_r1533858996)는 부분, 안드로이드 구현하며 아주 제대로 느꼈습니다. Coordinate(x,y)에 대한 도메인만 구현하고, 입력 조건이나 출력 조건이 수정되었을 때 View에서 처리해주어 도메인은 관련 없도록. 파싱이나 포메팅을 View에서 해주도록 수정했습니다. 저번 블랙잭 미션에서 제이든으로부터 첫 시야를 넓혔고, 이번에 페로로와 함께하며 더욱 생각이 명확해졌습니다. 감사합니다.
2. [ BlackTurn / WhiteTurn이 필요한가?](https://github.com/woowacourse/kotlin-omok/pull/57#discussion_r1539087970)
이에 대해 필요 없다고 깨달았습니다. BlackTurn 객체 안에서 BlackStone을 갖고, WhiteTurn 객체 안에서 WhiteStone을 갖는다는게 불필요하다는 것과, 개발자가 실수한다면 BlackTurn에 WhiteStone을 굳이 갖게 할 수도 있다는 오염 가능성, 두 턴의 룰이 똑같게 바뀐다면 굳이 따로 있을 필요도 없다는 것을 알게 되었습니다. 그래서 BlackTurn / WhiteTurn을 제거해주고 Playing 하나로 통합하며 인자로 turn을 갖게끔 했습니다. 그리고 이를 기반으로, 만약 렌주룰이 블랙턴에만 적용되는 것이 아닌 화이트턴에 적용되도록 Rule이 바뀐다면 그로 인해 도메인까지 바꿔줄 필요가 없고, 렌주룰이 두 턴 모두 똑같다면 불필요하게 두 턴 객체를 가질 필요도 없게 구조를 수정했습니다.
블랙턴에만 룰을 적용하는게 아니라, 화이트턴에 룰을 적용하게 된다면 라이브러리만 수정하면 되는데, 도메인까지 수정해야 했던 기존에 비해서 현재 코드는 개선되었습니다.
3. [어댑터 패턴 개념 활용](https://github.com/woowacourse/kotlin-omok/pull/57#discussion_r1539124591)
라이브러리와 보드의 결합이 강하다고 말씀해주신 부분에 동의하여, 라이브러리를 다시 원본으로 복원하였고,
라이브러리와 제 도메인을 연결해주는 OmokRuleMapper를 적용하였습니다.
결과적으로 룰과 보드와 턴이 강하게 의존되어있던 것을 분리하고자 했습니다.

### 이번 미션 구현 방식
- 제 게임 특성상 금수 위치를 사전에 X 처리 해주기 때문에, 매번 모든 위치를 다시 invalidate 하기에는 불필요할 수 있다고 생각되어 달라진 부분만 다시 그리도록 처리하고자 view의 tag를 활용했습니다.
- Repository 패턴을 적용하고자 했습니다. 또한 localDataSource는 Entity를 다루고, Repository 단에서 매핑 과정을 통해 실제 게임에서 쓰는 Coordinate로 변환했습니다.

### 현재 안타까운 것
- SQLite를 활용하면서 x와 y에 대한 값에 대해서만 통일성있게 사용하려다보니 마지막 돌에 대한 정보를 구별하여 저장할 곳이 떠오르지 않아서,
게임에서 placeStone을 할 때마다 db에 접근하여 돌을 저장하는 방식을 사용하고 있습니다. 
마지막 돌의 정보만 따로 저장한다면 이 방법 대신에 onPause에서 모두 한번에 저장하는게 IO 접근면에서 더 좋겠다고는 생각이 들었는데, 두 방법에 대해서 어떻게 생각하시나요??
- 함수의 가독성 순서에 대해서 잠깐 말씀해 주신 적이 있는데, 저는 Public을 모두 위에 두고 Private를 모두 아래에 두고자 하는 습관이 있습니다. 이 방법 말고 Public 아래에 해당 함수와 관련있는 Private를 두는 방법도 있다고 생각하는데, 두 방법에 대해 어떻게 생각하시나요??

긴 글 읽어주셔서 감사합니다. 정말 많이 배웠습니다.

2024-03-31 10:52 UTC, laco-dev requested changes
3, 4단계 고생 많으셨습니다.
레포지터리나 데이터 소스 분리한 시도 좋았습니다. 어느정도 알고 계시네요.
다만 이쪽은 현재 피드백 대상이 아니기 때문에 따로 내용을 남기지는 않았어요.
집중해야 할 내용에 필요한 리소스가 낭비될 수 있으니까요. 레벨 2에서 받아보시면 됩니다.

도메인 관점보다는 어떻게 활용했는지 위주로 보았습니다.
데이터를 저장할 때 좌표들만 주고 받는 대신 보드판 전체를 그리기 위한 테이블로 설계해보면 어떨까 합니다.

좌표들만으로는 보드를 그릴 수가 없기 때문에 비즈니스 로직이 결합되어야만 하니까요.

2024-03-31 10:52 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/data/repository/RepositoryImpl.kt
> +            CoordinateMapper.map(this)
파라미터로 들어온 coordinate를 그대로 반환하는 것 같은데 Mapper가 왜 필요한가요?

2024-03-31 10:52 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/model/Board.kt
> +        private set
게임 진행상황을 쭉 판단하고 있는 GameManager가 있다면, 현재 턴은 GameManager가 관리할 수 있지 않을까요?

2024-03-31 10:52 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/model/state/CoordinateState.kt
> +    data object WhiteStone : CoordinateState
이미 정의되어있는 Turn을 사용하면 나중에 다른 색깔의 돌이 추가되더라도, 문제가 없겠죠?
```kotlin
data class Placed(val turn: Turn): CoordinateState

data object Forbidden: CoordinateState
```

2024-03-31 10:52 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/model/state/GameState.kt
> +    abstract fun getNextTurn(placeResult: PlaceResult): GameState
외부에서 사용되지 않는다면 protected 접근자를 붙이면 됩니다.

2024-03-31 10:52 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/ui/MainActivity.kt
> +    }
> 함수의 가독성 순서에 대해서 잠깐 말씀해 주신 적이 있는데, 저는 Public을 모두 위에 두고 Private를 모두 아래에 두고자 하는 습관이 있습니다. 이 방법 말고 Public 아래에 해당 함수와 관련있는 Private를 두는 방법도 있다고 생각하는데, 두 방법에 대해 어떻게 생각하시나요??

후자가 맞습니다.
코드를 읽는 사람의 관점에서 봤을 때 `initViews()`가 바로 아래에 있는 것과 클래스 맨 밑에 있는 것중 무엇이 가독성이 좋을까요?

2024-03-31 10:52 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/model/Board.kt
> +        get() = _boardLayout
x, y (Coordinate) 좌표에 어떤 상태를 가지고 있다를 표현한다면, Map 자료구조를 사용하는게 더 효율적일 수 있습니다.

2024-03-31 10:52 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/ui/MainActivity.kt
> +        }
> 제 게임 특성상 금수 위치를 사전에 X 처리 해주기 때문에, 매번 모든 위치를 다시 invalidate 하기에는 불필요할 수 있다고 생각되어 달라진 부분만 다시 그리도록 처리하고자 view의 tag를 활용했습니다.

가급적 View의 Tag는 사용을 지양하는게 좋아서 남겨드립니다.
Block 좌표들에 대해서도 별도로 관리한다면, 도메인적으로 해석할 수 있으니 더 유리할 것 같습니다.
논리적으로 Block 이었던 좌표들은 돌이 없을테니까요.

```kotlin
private var lastBlockCoordinates: Collection<Coordinate>

lastsBlockCoordinates.forEach { removeBlockDrawable(...) }
val nextBlockCoordinates = gameState.getBlockCoordinates()
...
lastBlockCoordinates.foo { ... }
```

2024-03-31 10:52 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/ui/MainActivity.kt
> +            }
반복되는 스낵바 처리 로직을 별도 함수로 분리해주세요.
이런 경우가 고차 함수를 사용하기에 적절합니다.

```kotlin
showSnackBar(
   message = getString(R.string.game_over),
   action = R.string.restart,
   onAction = { replay() }
)
```

2024-03-31 10:52 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/utils/OmokRuleMapper.kt
> +class OmokRuleMapper {
도메인에서 필요한 것 같은데, 도메인과 라이브러리를 연결해주는 어댑터 성격이 utils 패키지에 위치하는게 맞을까요?

2024-03-31 10:52 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/ui/MainActivity.kt
> +        createVectorDrawable(applicationContext, R.drawable.black_stone)
RepositoryImpl(this) 에 들어가는 this와 이 코드에 들어가는 applicationContext는 어떤 차이가 있나요?

2024-03-31 10:52 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/ui/MainActivity.kt
> +    }
게임 플레이 상태를 액티비티가 인터페이스 구현하도록 잘 만들어 주셨어요 👍🏻

2024-03-31 10:52 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/data/local/entity/OmokEntity.kt
> +    val id: Long? = null,
id가 없는건 어떤 상황일까요?

2024-04-01 05:55 UTC, Hevton commented on app/src/main/java/woowacourse/omok/ui/GameManager.kt
> +            }
맞습니다 페로로. 미션을 구현하면서 해당 부분을 꽤나 오래 고민했었습니다.
SQLite만을 활용해보는 시점에서, 어떻게 하면 게임 데이터를 잘 저장할 수 있을까 였는데요..!

1. x, y 좌표값만을 저장한다
현재처럼 placeStone을 할 때마다 DB에 차곡차곡 순서대로 x y 좌표값을 저장하면, 턴을 저장할 필요나 상태를 저장할 필요가 없고, 맨 처음 돌이 무조건 블랙이므로 리스트의 순서대로 턴을 번갈아가면 돌의 색상을 저장할 필요도 없다고 생각했습니다.

2. Board를 저장한다.
lastCoordinate, current Turn,Coordinate,Stone 그리고 턴의 상태(게임이 진행중인지 끝났는지 여부까지)를 저장해야 하고, 제 게임에서 돌의 위치 뿐 아니라 금수의 위치까지 저장해야 하므로 직렬화/역직렬화를 사용하지 않는 한 SQLite만을 이용한 활용에서는 구조가 오히려 복잡해질 수도 있겠다고 생각했습니다.

그래서 비교를 통해 1번을 채택하게 되었는데, 이에 대한 페로로의 의견이 궁금합니다.

2024-04-01 05:56 UTC, Hevton commented on app/src/main/java/woowacourse/omok/ui/GameManager.kt
> +        saveCoordinate(coordinate)
1. 서버에서 저장해야 한다면 돌을 놓을 때마다 매번 저장해야 하긴 하겠네요!! 감사합니다.
2. placeStone 때마다 돌을 순서대로 넣지 않고, onPause() 때 List<List<CoordinateState>> 를 저장한다면 순서 보장이 안되기 때문이라고 생각했습니다.

2024-04-01 05:58 UTC, Hevton commented on app/src/main/java/woowacourse/omok/data/repository/RepositoryImpl.kt
> +            CoordinateMapper.map(this)
어플리케이션 단에 쓰이는 도메인 객체와 Entity 객체를 의미상으로 분리하고자 했습니다.

2024-04-01 06:03 UTC, Hevton commented on app/src/main/java/woowacourse/omok/model/Board.kt
> +        private set
GameManager에서는 턴을 갖고 있고, 턴을 업데이트해줍니다.
`gameState = gameState.placeStone()`
그리고 GameState에서 능동적으로 `현재 어떤 턴`인지 알고 있고, 그를 기반으로 `Board에 어떤 돌을 놓을 것인지`를 결정해주기 때문에 이렇게 설계했는데요!

따라서 현재
GameManager -> GameState -> Board 이렇게 턴을 알고 있다고 봐도 무방하다고 생각하는데, 제가 어색하게 활용한 부분이 있을까요?

2024-04-01 06:41 UTC, Hevton commented on app/src/main/java/woowacourse/omok/model/state/GameState.kt
> +    abstract fun getNextTurn(placeResult: PlaceResult): GameState
이 부분이 이해가 어려워서, 조금 더 설명을 요청드려도 될까요?

2024-04-01 06:42 UTC, Hevton commented on app/src/main/java/woowacourse/omok/ui/MainActivity.kt
> +    }
initView가 바로 아래에 있는 것이 가독성이 좋다고 생각합니다. 감사합니다!

2024-04-01 06:47 UTC, Hevton commented on app/src/main/java/woowacourse/omok/model/Board.kt
> +        get() = _boardLayout
Map<Coordinate, CoordinateState> 를 생각해 볼 수도 있겠네요..!

2024-04-01 07:18 UTC, Hevton commented on app/src/main/java/woowacourse/omok/ui/MainActivity.kt
> +            }
감사합니다

2024-04-02 03:52 UTC, Hevton commented on app/src/main/java/woowacourse/omok/model/state/GameState.kt
> +        }
감사합니다!

1. rule의 불변성을 보장할 수 있는, copy 메서드처럼 Board에 관한 정보를 전부 복사하는 대신 rule만 바꿔서 Board 객체를 새로 생성하는 방법과
2. 지금처럼 setRule 을 통해 동적으로 룰만 바꿔주며 턴을 번갈아가는 방법

두 가지 방법이 있겠다고 생각했습니다.

data 클래스처럼 copy(변경할값=변경값) 으로 새로 객체를 매번 생성하는 것과
일반 클래스에서 var의 값을 변경해주는 것과 같은 이야기라고 생각이 들었습니다.

저는 턴이 매우 빈번하게 바뀌기 때문에 객체를 매번 생성하는 대신에 2번의 방법을 적용했는데요.
혹시 동적으로 룰을 적용하는 등 이 방식을 지양해야 할까요??

2024-04-02 04:21 UTC, Hevton commented on app/src/main/java/woowacourse/omok/model/state/CoordinateState.kt
> +    data object WhiteStone : CoordinateState
저보다 제 코드를 더 잘 이해하고 계신 것 같아서 개탄스럽네요...!
분발하겠습니다.

2024-04-02 04:30 UTC, Hevton commented on app/src/main/java/woowacourse/omok/model/state/GameState.kt
> +    abstract fun getNextTurn(placeResult: PlaceResult): GameState
감사합니다. placeStone은 외부에서 사용하기에 그대로 두었고, getNextTurn은 서브클래스에서만 사용하기 때문에 protected 접근자를 붙여주었습니다.

2024-04-02 04:53 UTC, Hevton commented on app/src/main/java/woowacourse/omok/ui/MainActivity.kt
> +        }
페로로 안녕하세요, View의 Tag를 가능한 사용하지 않는 이유는 메모리 때문인가요?
사실 생각해보니 ViewHolder는 findViewById의 큰 단점을 보완하기 위해 View의 Tag를 사용한다면, 제가 사용한 방식은 '굳이' 라는 느낌이 들긴 하네요

2024-04-02 05:29 UTC, Hevton commented on app/src/main/java/woowacourse/omok/utils/OmokRuleMapper.kt
> +class OmokRuleMapper {
사실 utils에 넣으면서도 고민을 했었는데, mapper라는 느낌이 도메인에 가도 될까 라는 의문이 있었던 것 같습니다. 제가 너무 겁을 먹었네요. 혹시 OmokRuleTest에서 OmokRuleMapper를 활용하여 테스트 하고 있는데, OmokRule과 OmokRuleMapper 테스트를 따로 분리하는 것이 나을까요?

2024-04-02 05:32 UTC, Hevton commented on app/src/main/java/woowacourse/omok/ui/MainActivity.kt
> +        createVectorDrawable(applicationContext, R.drawable.black_stone)
이 부분은 제가 크게 잘못했습니다.
applicationContext는 application의 생명주기를 따르므로 MainActivity에서만 사용되는 drawable은 this로 컨텍스트를 지정해줘야했습니다.

2024-04-02 05:33 UTC, Hevton commented on app/src/main/java/woowacourse/omok/data/local/entity/OmokEntity.kt
> +    val id: Long? = null,
SQLite를 이용해서 데이터를 넣어줄 때, id를 auto_increment 로 지정하여 자동으로 생성되게끔 지정했습니다.
따라서 db에 save 할 때 id를 null로 지정하여, 자동으로 생성될 수 있게 하기 위해서 사용했습니다.

2024-04-02 05:50 UTC, Hevton commented
페로로 안녕하세요! 해결한 부분엔 ❤️를, 더 얘기해보고 싶은 부분은 🚀 를 남겼습니다!
그리고 별개로, 제가 마지막 PR 이후로 브랜치면에서 손을 댄게 없는데도 git push가 rejected 되어서, force로 push를 했는데
혹시 이럴 경우 리뷰에 문제가 있을까 갑자기 걱정이 드네요..

2024-04-02 23:39 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/model/state/GameState.kt
> +        }
> data 클래스처럼 copy(변경할값=변경값) 으로 새로 객체를 매번 생성하는 것과
일반 클래스에서 var의 값을 변경해주는 것과 같은 이야기라고 생각이 들었습니다.

다릅니다 😓 
선택의 영역이지만, 어떤 방법을 선택할지는 여러번 경험을 통해 알아가시면 좋겠습니다.
(객체 생성 자체의 비용 vs 동적으로 바꾸는 비용)

여러가지 레퍼런스가 있으니 불변 객체와 가변 객체의 장단점을 조금 더 찾아보세요.
추가로 턴이 빈번하게 바뀌더라도 룰이 영향을 받지 않도록 설계를 하면 룰이 매번 생성되지 않을 수도 있습니다.

2024-04-02 23:44 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/ui/GameManager.kt
> +            }
이 기능을 서버에서 구현하고 앱에서는 사용한다고 가정해보세요.
서버에서  저장한 좌표를 가져오고 앱에서는 돌을 하나씩 놓는게 좋은 방법일까요?

물론 지금의 요구사항에서는 이렇게 복잡하게 할 필요는 없지만 이 역시 데이터 구조 설계에 따라 조금 더 시야를 넓힐 수도 있습니다.

```kotlin
class Stone(val coordinate: Coordinate, val color: Color)
class StoneEntity(val x: Int, val y: Int, val color: String)

val stones: List<Stone> = dao.getStones()

// Board
class Board(width, height, stones: Stones)
val lastStone = stones.last()
val lastTurn = getTrunByStone(lastSone)
val currnetTurn = lastTurn.next()
```

2024-04-02 23:48 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/model/Board.kt
> +        get() = _boardLayout
`List<List<*>>`가 나쁜 방법은 아니지만, 알고리즘적으로 접근했을 때 크기만 알고 있다면 내가 둔 돌들에 대해서만 저장하는 방법도 있습니다.
불필요하게 모든 엘리먼트를 미리 만들거나 이중배열의 순회를 피할수도 있으니까요.

```kotlin
val stones: List<Stone> // 내가 지금까지 둔 돌들의 컬렉션
```

2024-04-02 23:50 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/ui/MainActivity.kt
> +        }
tag는 뷰 인스턴스에 저장하는 개념이라 UI 내부적으로 필요한 경우 종종 쓰입니다.
하지만 지금 구현하는 것은 View에 태그를 하는 것이 아닌 도메인적으로 구현을 하는 과정입니다.

그렇기 때문에 뷰에 직접 제어를 하는 방법이 아닌 기능적으로 풀이하기를 기대했습니다.
태그를 이용해 접근하는 것은 클래스 변수 하나 만들어두고 돌려쓰는 것 같이 보이니까요
```kotlin

class Animal {
   var name: String
}

val animal = Animal()
if (animal.name == "사자") { ... }
```

2024-04-02 23:51 UTC, laco-dev commented on app/src/main/java/woowacourse/omok/utils/OmokRuleMapper.kt
> +class OmokRuleMapper {
유틸이 왜 도메인과 데이터를 연결해주는 건가요?
같은 맥락이면, 여러 패키지 참조하면 모두다 유틸인가요?

MVC 패턴 등에서 찾아볼 수 있는 DAO 패턴의 Mapper가 일반적으로 어디에 위치해야 할지 묻는 것입니다.

2024-04-02 23:53 UTC, laco-dev approved these changes
미션 기간이 끝난 뒤라, 남겨주신 질문에 대해서만 답변을 남겨드렸습니다.

오목 미션이 그동안 한 미션보다 더 힘드셨을 것 같은데, 가지고 계신 기준과 이번에 새로 알게된 것들 역시 모두 정답은 아닐 수 있으니 조금 더 경험과 레퍼런스를 만들고 자신만의 기준을 찾아 가시면 좋겠습니다.

이후 레벨 2미션도 응원하겠습니다.

2024-04-02 23:53 UTC, merged